# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .app_category import AppCategory
from .app_id import AppId


class App(UncheckedBaseModel):
    """
    An app an inbox can sign in to.
    """

    app_id: AppId
    name: typing.Optional[str] = None
    updated_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Time at which app was last updated.
    """

    description: typing.Optional[str] = None
    logo_url: typing.Optional[str] = None
    terms_url: typing.Optional[str] = None
    privacy_url: typing.Optional[str] = None
    categories: typing.Optional[typing.List[AppCategory]] = pydantic.Field(default=None)
    """
    Kinds of app, up to 3. Omitted when the app sets none.
    """

    owner_signup_limit: typing.Optional[int] = pydantic.Field(default=None)
    """
    Maximum number of accounts your organization may sign up at this app. Omitted when the app sets no limit. 0 means the app has paused new sign-ups; existing accounts keep signing in.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
