# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .client_id import ClientId
    from .create_inbox_webhook_request import CreateInboxWebhookRequest
    from .create_pod_webhook_request import CreatePodWebhookRequest
    from .create_webhook_event_types import CreateWebhookEventTypes
    from .create_webhook_request import CreateWebhookRequest
    from .list_webhooks_response import ListWebhooksResponse
    from .update_inbox_webhook_request import UpdateInboxWebhookRequest
    from .update_pod_webhook_request import UpdatePodWebhookRequest
    from .update_webhook_event_types import UpdateWebhookEventTypes
    from .update_webhook_headers_request import UpdateWebhookHeadersRequest
    from .update_webhook_request import UpdateWebhookRequest
    from .url import Url
    from .webhook import Webhook
    from .webhook_header_names_response import WebhookHeaderNamesResponse
    from .webhook_headers import WebhookHeaders
    from .webhook_id import WebhookId
_dynamic_imports: typing.Dict[str, str] = {
    "ClientId": ".client_id",
    "CreateInboxWebhookRequest": ".create_inbox_webhook_request",
    "CreatePodWebhookRequest": ".create_pod_webhook_request",
    "CreateWebhookEventTypes": ".create_webhook_event_types",
    "CreateWebhookRequest": ".create_webhook_request",
    "ListWebhooksResponse": ".list_webhooks_response",
    "UpdateInboxWebhookRequest": ".update_inbox_webhook_request",
    "UpdatePodWebhookRequest": ".update_pod_webhook_request",
    "UpdateWebhookEventTypes": ".update_webhook_event_types",
    "UpdateWebhookHeadersRequest": ".update_webhook_headers_request",
    "UpdateWebhookRequest": ".update_webhook_request",
    "Url": ".url",
    "Webhook": ".webhook",
    "WebhookHeaderNamesResponse": ".webhook_header_names_response",
    "WebhookHeaders": ".webhook_headers",
    "WebhookId": ".webhook_id",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ClientId",
    "CreateInboxWebhookRequest",
    "CreatePodWebhookRequest",
    "CreateWebhookEventTypes",
    "CreateWebhookRequest",
    "ListWebhooksResponse",
    "UpdateInboxWebhookRequest",
    "UpdatePodWebhookRequest",
    "UpdateWebhookEventTypes",
    "UpdateWebhookHeadersRequest",
    "UpdateWebhookRequest",
    "Url",
    "Webhook",
    "WebhookHeaderNamesResponse",
    "WebhookHeaders",
    "WebhookId",
]
