# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...events.types.pod_ids import PodIds
from .create_pod_webhook_request import CreatePodWebhookRequest


class CreateWebhookRequest(CreatePodWebhookRequest):
    pod_ids: typing.Optional[PodIds] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
