# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .webhook_headers import WebhookHeaders


class UpdateWebhookHeadersRequest(UncheckedBaseModel):
    """
    Set, replace, or remove custom delivery headers. Provide at least one of `headers` or
    `remove_headers`. A header cannot be set and removed in the same request, regardless of casing.
    """

    headers: typing.Optional[WebhookHeaders] = None
    remove_headers: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Names of custom delivery headers to remove.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
