# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...events.types.inbox_ids import InboxIds
from .update_inbox_webhook_request import UpdateInboxWebhookRequest


class UpdatePodWebhookRequest(UpdateInboxWebhookRequest):
    """
    Update a pod-scoped webhook. You can adjust which inboxes within the pod it listens to, replace
    its `event_types`, and set `enabled`, but not change the pod scope itself.
    """

    add_inbox_ids: typing.Optional[InboxIds] = pydantic.Field(default=None)
    """
    Inbox IDs to subscribe to the webhook. This only adds to what the webhook receives: on a webhook
    that covers its whole pod, it changes nothing. To receive only specific inboxes, create a webhook
    with `inbox_ids` instead.
    """

    remove_inbox_ids: typing.Optional[InboxIds] = pydantic.Field(default=None)
    """
    Inbox IDs to unsubscribe from the webhook.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
