# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from ...events.types.event_types import EventTypes
from ...events.types.inbox_ids import InboxIds
from ...events.types.pod_ids import PodIds
from .client_id import ClientId
from .url import Url
from .webhook_id import WebhookId


class Webhook(UncheckedBaseModel):
    webhook_id: WebhookId
    url: Url
    event_types: typing.Optional[EventTypes] = None
    pod_ids: typing.Optional[PodIds] = None
    inbox_ids: typing.Optional[InboxIds] = None
    pod_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    ID of the pod the webhook belongs to: the pod it was created in, or the pod of the inbox it
    belongs to. Absent for an organization webhook and on some inbox webhooks. This is not the
    list of pods it receives events for; see `pod_ids`.
    """

    inbox_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    ID of the inbox the webhook belongs to, if it was created for an inbox. This is not the list
    of inboxes it receives events for; see `inbox_ids`.
    """

    secret: str = pydantic.Field()
    """
    Secret for webhook signature verification.
    """

    enabled: bool = pydantic.Field()
    """
    Webhook is enabled.
    """

    updated_at: dt.datetime = pydantic.Field()
    """
    Time at which webhook was last updated.
    """

    created_at: dt.datetime = pydantic.Field()
    """
    Time at which webhook was created.
    """

    client_id: typing.Optional[ClientId] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
