# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from ...pods.types.pod_id import PodId
from .client_id import ClientId
from .domain_id import DomainId
from .domain_name import DomainName
from .feedback_enabled import FeedbackEnabled
from .status import Status
from .subdomains_enabled import SubdomainsEnabled
from .tracking_enabled import TrackingEnabled
from .verification_record import VerificationRecord


class Domain(UncheckedBaseModel):
    pod_id: typing.Optional[PodId] = None
    domain_id: DomainId
    domain: DomainName
    status: Status
    reason: typing.Optional[str] = pydantic.Field(default=None)
    """
    Why the domain is not (yet) VERIFIED, when known. `dns_records_missing` / `dns_records_invalid` point at the DNS records. The `ses_*` values mean the records look right and sending-infrastructure validation has not converged: `ses_dkim_pending` / `ses_mail_from_pending` (still checking), `ses_dkim_temporary_failure` / `ses_mail_from_temporary_failure` (a transient error the infrastructure keeps retrying on its own — usually resolves without changes), `ses_dkim_failed` / `ses_mail_from_failed` (a terminal verdict; re-verify after fixing), `ses_dkim_not_started` / `ses_mail_from_not_started` (the attribute was never configured on the identity — re-verify to push it), and `ses_not_verified_for_sending`. Absent when VERIFIED.
    """

    feedback_enabled: FeedbackEnabled
    subdomains_enabled: SubdomainsEnabled
    tracking_enabled: TrackingEnabled
    records: typing.List[VerificationRecord] = pydantic.Field()
    """
    A list of DNS records required to verify the domain. Includes a
    wildcard MX record (`*.<domain>`) when `subdomains_enabled` is true.
    """

    client_id: typing.Optional[ClientId] = None
    updated_at: dt.datetime = pydantic.Field()
    """
    Time at which the domain was last updated.
    """

    created_at: dt.datetime = pydantic.Field()
    """
    Time at which the domain was created.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
