# This file was auto-generated by Fern from our API Definition.

import typing

from ..attachments.types.attachment_id import AttachmentId
from ..attachments.types.attachment_response import AttachmentResponse
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.after import After
from ..types.ascending import Ascending
from ..types.before import Before
from ..types.include_blocked import IncludeBlocked
from ..types.include_spam import IncludeSpam
from ..types.include_trash import IncludeTrash
from ..types.include_unauthenticated import IncludeUnauthenticated
from ..types.labels import Labels
from ..types.limit import Limit
from ..types.page_token import PageToken
from ..types.query import Query
from .raw_client import AsyncRawThreadsClient, RawThreadsClient
from .types.list_threads_response import ListThreadsResponse
from .types.search_threads_response import SearchThreadsResponse
from .types.thread import Thread
from .types.thread_id import ThreadId
from .types.update_thread_response import UpdateThreadResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ThreadsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawThreadsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawThreadsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawThreadsClient
        """
        return self._raw_client

    def list(
        self,
        *,
        limit: typing.Optional[Limit] = None,
        page_token: typing.Optional[PageToken] = None,
        labels: typing.Optional[Labels] = None,
        before: typing.Optional[Before] = None,
        after: typing.Optional[After] = None,
        ascending: typing.Optional[Ascending] = None,
        include_spam: typing.Optional[IncludeSpam] = None,
        include_blocked: typing.Optional[IncludeBlocked] = None,
        include_unauthenticated: typing.Optional[IncludeUnauthenticated] = None,
        include_trash: typing.Optional[IncludeTrash] = None,
        senders: typing.Optional[typing.Sequence[str]] = None,
        recipients: typing.Optional[typing.Sequence[str]] = None,
        subject: typing.Optional[typing.Sequence[str]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListThreadsResponse:
        """
        Lists threads, most recent first. Pass `senders`, `recipients`, or
        `subject` to filter by substring. Filtered requests are served by
        search, which caps `limit` at 100. For relevance-ranked full-text
        search across senders, recipients, subject, and message body, use
        `Search Threads`.

        **CLI:**
        ```bash
        agentmail threads list
        ```

        Parameters
        ----------
        limit : typing.Optional[Limit]

        page_token : typing.Optional[PageToken]

        labels : typing.Optional[Labels]

        before : typing.Optional[Before]

        after : typing.Optional[After]

        ascending : typing.Optional[Ascending]

        include_spam : typing.Optional[IncludeSpam]

        include_blocked : typing.Optional[IncludeBlocked]

        include_unauthenticated : typing.Optional[IncludeUnauthenticated]

        include_trash : typing.Optional[IncludeTrash]

        senders : typing.Optional[typing.Sequence[str]]
            Filter to threads whose senders contain this value (substring match). Repeatable; all values must match.

        recipients : typing.Optional[typing.Sequence[str]]
            Filter to threads whose recipients contain this value (substring match). Repeatable; all values must match.

        subject : typing.Optional[typing.Sequence[str]]
            Filter to threads whose subject contains this value (substring match). Repeatable; all values must match.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListThreadsResponse

        Examples
        --------
        from agentmail import AgentMail

        client = AgentMail(
            api_key="YOUR_API_KEY",
        )
        client.threads.list()
        """
        _response = self._raw_client.list(
            limit=limit,
            page_token=page_token,
            labels=labels,
            before=before,
            after=after,
            ascending=ascending,
            include_spam=include_spam,
            include_blocked=include_blocked,
            include_unauthenticated=include_unauthenticated,
            include_trash=include_trash,
            senders=senders,
            recipients=recipients,
            subject=subject,
            request_options=request_options,
        )
        return _response.data

    def search(
        self,
        *,
        q: Query,
        limit: typing.Optional[Limit] = None,
        page_token: typing.Optional[PageToken] = None,
        before: typing.Optional[Before] = None,
        after: typing.Optional[After] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SearchThreadsResponse:
        """
        Full-text search across threads in the organization, ranked by
        relevance. The query is matched against senders, recipients, and
        subject (substring) and the message body (tokenized full text). Spam,
        trash, blocked, and unauthenticated threads are always excluded.
        `limit` cannot exceed 100.

        Parameters
        ----------
        q : Query

        limit : typing.Optional[Limit]

        page_token : typing.Optional[PageToken]

        before : typing.Optional[Before]

        after : typing.Optional[After]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchThreadsResponse

        Examples
        --------
        from agentmail import AgentMail

        client = AgentMail(
            api_key="YOUR_API_KEY",
        )
        client.threads.search(
            q="q",
        )
        """
        _response = self._raw_client.search(
            q=q, limit=limit, page_token=page_token, before=before, after=after, request_options=request_options
        )
        return _response.data

    def get(self, thread_id: ThreadId, *, request_options: typing.Optional[RequestOptions] = None) -> Thread:
        """
        **CLI:**
        ```bash
        agentmail threads get --thread-id <thread_id>
        ```

        Parameters
        ----------
        thread_id : ThreadId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Thread

        Examples
        --------
        from agentmail import AgentMail

        client = AgentMail(
            api_key="YOUR_API_KEY",
        )
        client.threads.get(
            thread_id="thread_id",
        )
        """
        _response = self._raw_client.get(thread_id, request_options=request_options)
        return _response.data

    def get_attachment(
        self,
        thread_id: ThreadId,
        attachment_id: AttachmentId,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AttachmentResponse:
        """
        **CLI:**
        ```bash
        agentmail threads get-attachment --thread-id <thread_id> --attachment-id <attachment_id>
        ```

        Parameters
        ----------
        thread_id : ThreadId

        attachment_id : AttachmentId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AttachmentResponse

        Examples
        --------
        from agentmail import AgentMail

        client = AgentMail(
            api_key="YOUR_API_KEY",
        )
        client.threads.get_attachment(
            thread_id="thread_id",
            attachment_id="attachment_id",
        )
        """
        _response = self._raw_client.get_attachment(thread_id, attachment_id, request_options=request_options)
        return _response.data

    def update(
        self,
        thread_id: ThreadId,
        *,
        add_labels: typing.Optional[typing.Sequence[str]] = OMIT,
        remove_labels: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateThreadResponse:
        """
        Updates thread labels. Cannot add or remove system labels (sent, received, bounced, etc.). Rejects requests with a `422` for threads with 100 or more messages.

        Parameters
        ----------
        thread_id : ThreadId

        add_labels : typing.Optional[typing.Sequence[str]]
            Labels to add to thread. Cannot be system labels.

        remove_labels : typing.Optional[typing.Sequence[str]]
            Labels to remove from thread. Cannot be system labels. Takes priority over `add_labels` (in the event of duplicate labels passed in).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateThreadResponse

        Examples
        --------
        from agentmail import AgentMail

        client = AgentMail(
            api_key="YOUR_API_KEY",
        )
        client.threads.update(
            thread_id="thread_id",
        )
        """
        _response = self._raw_client.update(
            thread_id, add_labels=add_labels, remove_labels=remove_labels, request_options=request_options
        )
        return _response.data

    def delete(self, thread_id: ThreadId, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Permanently deletes a thread and all of its messages.

        **CLI:**
        ```bash
        agentmail threads delete --thread-id <thread_id>
        ```

        Parameters
        ----------
        thread_id : ThreadId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from agentmail import AgentMail

        client = AgentMail(
            api_key="YOUR_API_KEY",
        )
        client.threads.delete(
            thread_id="thread_id",
        )
        """
        _response = self._raw_client.delete(thread_id, request_options=request_options)
        return _response.data


class AsyncThreadsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawThreadsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawThreadsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawThreadsClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        limit: typing.Optional[Limit] = None,
        page_token: typing.Optional[PageToken] = None,
        labels: typing.Optional[Labels] = None,
        before: typing.Optional[Before] = None,
        after: typing.Optional[After] = None,
        ascending: typing.Optional[Ascending] = None,
        include_spam: typing.Optional[IncludeSpam] = None,
        include_blocked: typing.Optional[IncludeBlocked] = None,
        include_unauthenticated: typing.Optional[IncludeUnauthenticated] = None,
        include_trash: typing.Optional[IncludeTrash] = None,
        senders: typing.Optional[typing.Sequence[str]] = None,
        recipients: typing.Optional[typing.Sequence[str]] = None,
        subject: typing.Optional[typing.Sequence[str]] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListThreadsResponse:
        """
        Lists threads, most recent first. Pass `senders`, `recipients`, or
        `subject` to filter by substring. Filtered requests are served by
        search, which caps `limit` at 100. For relevance-ranked full-text
        search across senders, recipients, subject, and message body, use
        `Search Threads`.

        **CLI:**
        ```bash
        agentmail threads list
        ```

        Parameters
        ----------
        limit : typing.Optional[Limit]

        page_token : typing.Optional[PageToken]

        labels : typing.Optional[Labels]

        before : typing.Optional[Before]

        after : typing.Optional[After]

        ascending : typing.Optional[Ascending]

        include_spam : typing.Optional[IncludeSpam]

        include_blocked : typing.Optional[IncludeBlocked]

        include_unauthenticated : typing.Optional[IncludeUnauthenticated]

        include_trash : typing.Optional[IncludeTrash]

        senders : typing.Optional[typing.Sequence[str]]
            Filter to threads whose senders contain this value (substring match). Repeatable; all values must match.

        recipients : typing.Optional[typing.Sequence[str]]
            Filter to threads whose recipients contain this value (substring match). Repeatable; all values must match.

        subject : typing.Optional[typing.Sequence[str]]
            Filter to threads whose subject contains this value (substring match). Repeatable; all values must match.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListThreadsResponse

        Examples
        --------
        import asyncio

        from agentmail import AsyncAgentMail

        client = AsyncAgentMail(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.threads.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            limit=limit,
            page_token=page_token,
            labels=labels,
            before=before,
            after=after,
            ascending=ascending,
            include_spam=include_spam,
            include_blocked=include_blocked,
            include_unauthenticated=include_unauthenticated,
            include_trash=include_trash,
            senders=senders,
            recipients=recipients,
            subject=subject,
            request_options=request_options,
        )
        return _response.data

    async def search(
        self,
        *,
        q: Query,
        limit: typing.Optional[Limit] = None,
        page_token: typing.Optional[PageToken] = None,
        before: typing.Optional[Before] = None,
        after: typing.Optional[After] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SearchThreadsResponse:
        """
        Full-text search across threads in the organization, ranked by
        relevance. The query is matched against senders, recipients, and
        subject (substring) and the message body (tokenized full text). Spam,
        trash, blocked, and unauthenticated threads are always excluded.
        `limit` cannot exceed 100.

        Parameters
        ----------
        q : Query

        limit : typing.Optional[Limit]

        page_token : typing.Optional[PageToken]

        before : typing.Optional[Before]

        after : typing.Optional[After]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SearchThreadsResponse

        Examples
        --------
        import asyncio

        from agentmail import AsyncAgentMail

        client = AsyncAgentMail(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.threads.search(
                q="q",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.search(
            q=q, limit=limit, page_token=page_token, before=before, after=after, request_options=request_options
        )
        return _response.data

    async def get(self, thread_id: ThreadId, *, request_options: typing.Optional[RequestOptions] = None) -> Thread:
        """
        **CLI:**
        ```bash
        agentmail threads get --thread-id <thread_id>
        ```

        Parameters
        ----------
        thread_id : ThreadId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Thread

        Examples
        --------
        import asyncio

        from agentmail import AsyncAgentMail

        client = AsyncAgentMail(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.threads.get(
                thread_id="thread_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(thread_id, request_options=request_options)
        return _response.data

    async def get_attachment(
        self,
        thread_id: ThreadId,
        attachment_id: AttachmentId,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AttachmentResponse:
        """
        **CLI:**
        ```bash
        agentmail threads get-attachment --thread-id <thread_id> --attachment-id <attachment_id>
        ```

        Parameters
        ----------
        thread_id : ThreadId

        attachment_id : AttachmentId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AttachmentResponse

        Examples
        --------
        import asyncio

        from agentmail import AsyncAgentMail

        client = AsyncAgentMail(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.threads.get_attachment(
                thread_id="thread_id",
                attachment_id="attachment_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_attachment(thread_id, attachment_id, request_options=request_options)
        return _response.data

    async def update(
        self,
        thread_id: ThreadId,
        *,
        add_labels: typing.Optional[typing.Sequence[str]] = OMIT,
        remove_labels: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateThreadResponse:
        """
        Updates thread labels. Cannot add or remove system labels (sent, received, bounced, etc.). Rejects requests with a `422` for threads with 100 or more messages.

        Parameters
        ----------
        thread_id : ThreadId

        add_labels : typing.Optional[typing.Sequence[str]]
            Labels to add to thread. Cannot be system labels.

        remove_labels : typing.Optional[typing.Sequence[str]]
            Labels to remove from thread. Cannot be system labels. Takes priority over `add_labels` (in the event of duplicate labels passed in).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateThreadResponse

        Examples
        --------
        import asyncio

        from agentmail import AsyncAgentMail

        client = AsyncAgentMail(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.threads.update(
                thread_id="thread_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            thread_id, add_labels=add_labels, remove_labels=remove_labels, request_options=request_options
        )
        return _response.data

    async def delete(self, thread_id: ThreadId, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Permanently deletes a thread and all of its messages.

        **CLI:**
        ```bash
        agentmail threads delete --thread-id <thread_id>
        ```

        Parameters
        ----------
        thread_id : ThreadId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from agentmail import AsyncAgentMail

        client = AsyncAgentMail(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.threads.delete(
                thread_id="thread_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(thread_id, request_options=request_options)
        return _response.data
