# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ...events.types.inbox_ids import InboxIds
from ...events.types.pod_ids import PodIds
from ...types.ascending import Ascending
from ...types.limit import Limit
from ...types.page_token import PageToken
from ..types.create_webhook_event_types import CreateWebhookEventTypes
from ..types.webhook_id import WebhookId
from .raw_client import AsyncRawPollingClient, RawPollingClient
from .types.create_polling_webhook_response import CreatePollingWebhookResponse
from .types.list_polling_webhooks_response import ListPollingWebhooksResponse
from .types.polling_client_id import PollingClientId
from .types.polling_webhook import PollingWebhook

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class PollingClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPollingClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPollingClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPollingClient
        """
        return self._raw_client

    def list(
        self,
        *,
        limit: typing.Optional[Limit] = None,
        page_token: typing.Optional[PageToken] = None,
        ascending: typing.Optional[Ascending] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListPollingWebhooksResponse:
        """
        Lists the polling webhooks created through this route. `page_token` must come from this
        endpoint; a token from another list endpoint is rejected.

        **CLI:**
        ```bash
        agentmail webhooks polling list
        ```

        Parameters
        ----------
        limit : typing.Optional[Limit]

        page_token : typing.Optional[PageToken]

        ascending : typing.Optional[Ascending]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListPollingWebhooksResponse

        Examples
        --------
        from agentmail import AgentMail

        client = AgentMail(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.polling.list()
        """
        _response = self._raw_client.list(
            limit=limit, page_token=page_token, ascending=ascending, request_options=request_options
        )
        return _response.data

    def get(self, webhook_id: WebhookId, *, request_options: typing.Optional[RequestOptions] = None) -> PollingWebhook:
        """
        The `token` is never returned here: create again with the same `client_id` to get a new one.

        **CLI:**
        ```bash
        agentmail webhooks polling get --webhook-id <webhook_id>
        ```

        Parameters
        ----------
        webhook_id : WebhookId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PollingWebhook

        Examples
        --------
        from agentmail import AgentMail

        client = AgentMail(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.polling.get(
            webhook_id="webhook_id",
        )
        """
        _response = self._raw_client.get(webhook_id, request_options=request_options)
        return _response.data

    def create(
        self,
        *,
        client_id: PollingClientId,
        event_types: CreateWebhookEventTypes,
        pod_ids: typing.Optional[PodIds] = OMIT,
        inbox_ids: typing.Optional[InboxIds] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreatePollingWebhookResponse:
        """
        Creates a subscription the agent polls for events, and returns the `token` that reads it. Each
        organization, pod, and inbox holds at most 10 polling webhooks; a repeat create with the same
        `client_id` re-issues the token of the existing one instead of counting against that limit.

        **CLI:**
        ```bash
        agentmail webhooks polling create --client-id my-agent --event-types message.received
        ```

        Parameters
        ----------
        client_id : PollingClientId

        event_types : CreateWebhookEventTypes

        pod_ids : typing.Optional[PodIds]
            Pods for which to receive events. Maximum 10 channels (pods plus inboxes) per subscription. The
            subscription receives an event that matches any listed pod or inbox, so a listed pod already
            covers every inbox in it.

        inbox_ids : typing.Optional[InboxIds]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreatePollingWebhookResponse

        Examples
        --------
        from agentmail import AgentMail

        client = AgentMail(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.polling.create(
            client_id="client_id",
            event_types=["message.received", "message.received"],
        )
        """
        _response = self._raw_client.create(
            client_id=client_id,
            event_types=event_types,
            pod_ids=pod_ids,
            inbox_ids=inbox_ids,
            request_options=request_options,
        )
        return _response.data

    def delete(self, webhook_id: WebhookId, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Stops delivery and invalidates the subscription's token.

        **CLI:**
        ```bash
        agentmail webhooks polling delete --webhook-id <webhook_id>
        ```

        Parameters
        ----------
        webhook_id : WebhookId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from agentmail import AgentMail

        client = AgentMail(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.polling.delete(
            webhook_id="webhook_id",
        )
        """
        _response = self._raw_client.delete(webhook_id, request_options=request_options)
        return _response.data


class AsyncPollingClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPollingClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPollingClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPollingClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        limit: typing.Optional[Limit] = None,
        page_token: typing.Optional[PageToken] = None,
        ascending: typing.Optional[Ascending] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListPollingWebhooksResponse:
        """
        Lists the polling webhooks created through this route. `page_token` must come from this
        endpoint; a token from another list endpoint is rejected.

        **CLI:**
        ```bash
        agentmail webhooks polling list
        ```

        Parameters
        ----------
        limit : typing.Optional[Limit]

        page_token : typing.Optional[PageToken]

        ascending : typing.Optional[Ascending]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListPollingWebhooksResponse

        Examples
        --------
        import asyncio

        from agentmail import AsyncAgentMail

        client = AsyncAgentMail(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.polling.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            limit=limit, page_token=page_token, ascending=ascending, request_options=request_options
        )
        return _response.data

    async def get(
        self, webhook_id: WebhookId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PollingWebhook:
        """
        The `token` is never returned here: create again with the same `client_id` to get a new one.

        **CLI:**
        ```bash
        agentmail webhooks polling get --webhook-id <webhook_id>
        ```

        Parameters
        ----------
        webhook_id : WebhookId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PollingWebhook

        Examples
        --------
        import asyncio

        from agentmail import AsyncAgentMail

        client = AsyncAgentMail(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.polling.get(
                webhook_id="webhook_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(webhook_id, request_options=request_options)
        return _response.data

    async def create(
        self,
        *,
        client_id: PollingClientId,
        event_types: CreateWebhookEventTypes,
        pod_ids: typing.Optional[PodIds] = OMIT,
        inbox_ids: typing.Optional[InboxIds] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreatePollingWebhookResponse:
        """
        Creates a subscription the agent polls for events, and returns the `token` that reads it. Each
        organization, pod, and inbox holds at most 10 polling webhooks; a repeat create with the same
        `client_id` re-issues the token of the existing one instead of counting against that limit.

        **CLI:**
        ```bash
        agentmail webhooks polling create --client-id my-agent --event-types message.received
        ```

        Parameters
        ----------
        client_id : PollingClientId

        event_types : CreateWebhookEventTypes

        pod_ids : typing.Optional[PodIds]
            Pods for which to receive events. Maximum 10 channels (pods plus inboxes) per subscription. The
            subscription receives an event that matches any listed pod or inbox, so a listed pod already
            covers every inbox in it.

        inbox_ids : typing.Optional[InboxIds]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreatePollingWebhookResponse

        Examples
        --------
        import asyncio

        from agentmail import AsyncAgentMail

        client = AsyncAgentMail(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.polling.create(
                client_id="client_id",
                event_types=["message.received", "message.received"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            client_id=client_id,
            event_types=event_types,
            pod_ids=pod_ids,
            inbox_ids=inbox_ids,
            request_options=request_options,
        )
        return _response.data

    async def delete(self, webhook_id: WebhookId, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Stops delivery and invalidates the subscription's token.

        **CLI:**
        ```bash
        agentmail webhooks polling delete --webhook-id <webhook_id>
        ```

        Parameters
        ----------
        webhook_id : WebhookId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from agentmail import AsyncAgentMail

        client = AsyncAgentMail(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.polling.delete(
                webhook_id="webhook_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(webhook_id, request_options=request_options)
        return _response.data
