# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .attachment_content_disposition import AttachmentContentDisposition
from .attachment_content_id import AttachmentContentId
from .attachment_content_type import AttachmentContentType
from .attachment_filename import AttachmentFilename


class SendAttachment(UncheckedBaseModel):
    """
    Provide either `content` or `url` for each attachment.
    """

    filename: typing.Optional[AttachmentFilename] = None
    content_type: typing.Optional[AttachmentContentType] = None
    content_disposition: typing.Optional[AttachmentContentDisposition] = None
    content_id: typing.Optional[AttachmentContentId] = None
    content: typing.Optional[str] = pydantic.Field(default=None)
    """
    Base64 encoded content of the attachment. The entire request, including the message body and all attachments, is limited to 6 MB.
    """

    url: typing.Optional[str] = pydantic.Field(default=None)
    """
    URL that AgentMail can download without custom authentication headers or cookies.
    Redirects and pre-signed URLs are supported, and the final response must be a
    successful 2xx response. Keep URL-backed attachments around 30 MB total per message.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
