# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...attachments.types.send_attachment import SendAttachment
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .draft_bcc import DraftBcc
from .draft_cc import DraftCc
from .draft_client_id import DraftClientId
from .draft_html import DraftHtml
from .draft_labels import DraftLabels
from .draft_reply_all import DraftReplyAll
from .draft_reply_to import DraftReplyTo
from .draft_send_at import DraftSendAt
from .draft_subject import DraftSubject
from .draft_text import DraftText
from .draft_to import DraftTo


class CreateDraftReplyRequest(UncheckedBaseModel):
    """
    Body for creating a draft that replies to a message. `in_reply_to`,
    `references`, and the subject are derived from the source message. Set
    `reply_all` to address the whole thread (you cannot then also pass `to`,
    `cc`, or `bcc`).
    """

    labels: typing.Optional[DraftLabels] = None
    reply_to: typing.Optional[DraftReplyTo] = None
    to: typing.Optional[DraftTo] = None
    cc: typing.Optional[DraftCc] = None
    bcc: typing.Optional[DraftBcc] = None
    reply_all: typing.Optional[DraftReplyAll] = None
    subject: typing.Optional[DraftSubject] = None
    text: typing.Optional[DraftText] = None
    html: typing.Optional[DraftHtml] = None
    attachments: typing.Optional[typing.List[SendAttachment]] = pydantic.Field(default=None)
    """
    Attachments to include in draft.
    """

    send_at: typing.Optional[DraftSendAt] = None
    client_id: typing.Optional[DraftClientId] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
