# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.serialization import FieldMetadata
from ...core.unchecked_base_model import UncheckedBaseModel


class SearchThreadHighlights(UncheckedBaseModel):
    """
    Matched fragments per field on a thread search result, with matched terms
    wrapped in `**`. A field key is present only when the query matched that
    field, so the present keys also tell you which fields produced the hit.
    """

    from_: typing_extensions.Annotated[
        typing.Optional[typing.List[str]],
        FieldMetadata(alias="from"),
        pydantic.Field(alias="from", description="Matched fragments from a sender address in the thread."),
    ] = None
    recipients: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Matched fragments from a recipient address in the thread (to, cc, or bcc).
    """

    subject: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Matched fragments from the subject.
    """

    text: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Matched fragments from a message body in the thread.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
