# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        Attendee,
        AttendeeRole,
        AttendeeStatus,
        Calendar,
        CalendarConsistency,
        CalendarEvent,
        CalendarEventId,
        CalendarEventKind,
        CalendarEventMutationResponse,
        CalendarEventSource,
        CalendarEventStatus,
        CalendarLimit,
        CreateCalendarEventRequest,
        DeleteCalendarEventResponse,
        DeletionId,
        DurationMode,
        IanaTimezone,
        IncludeOverlapping,
        InstanceMutationMode,
        ListCalendarEventsResponse,
        OperationId,
        PreconditionFailedErrorResponse,
        Recurrence,
        RecurrenceDate,
        RecurrenceInput,
        RecurrencePeriod,
        ResourceRevision,
        RespondCalendarEventRequest,
        RespondStatus,
        UpdateCalendarEventRequest,
        UpdateCalendarRequest,
        WallTime,
        WindowAfter,
        WindowBefore,
    )
    from .errors import EventExpiredError, ForbiddenError, PayloadTooLargeError, PreconditionFailedError, RateLimitError
_dynamic_imports: typing.Dict[str, str] = {
    "Attendee": ".types",
    "AttendeeRole": ".types",
    "AttendeeStatus": ".types",
    "Calendar": ".types",
    "CalendarConsistency": ".types",
    "CalendarEvent": ".types",
    "CalendarEventId": ".types",
    "CalendarEventKind": ".types",
    "CalendarEventMutationResponse": ".types",
    "CalendarEventSource": ".types",
    "CalendarEventStatus": ".types",
    "CalendarLimit": ".types",
    "CreateCalendarEventRequest": ".types",
    "DeleteCalendarEventResponse": ".types",
    "DeletionId": ".types",
    "DurationMode": ".types",
    "EventExpiredError": ".errors",
    "ForbiddenError": ".errors",
    "IanaTimezone": ".types",
    "IncludeOverlapping": ".types",
    "InstanceMutationMode": ".types",
    "ListCalendarEventsResponse": ".types",
    "OperationId": ".types",
    "PayloadTooLargeError": ".errors",
    "PreconditionFailedError": ".errors",
    "PreconditionFailedErrorResponse": ".types",
    "RateLimitError": ".errors",
    "Recurrence": ".types",
    "RecurrenceDate": ".types",
    "RecurrenceInput": ".types",
    "RecurrencePeriod": ".types",
    "ResourceRevision": ".types",
    "RespondCalendarEventRequest": ".types",
    "RespondStatus": ".types",
    "UpdateCalendarEventRequest": ".types",
    "UpdateCalendarRequest": ".types",
    "WallTime": ".types",
    "WindowAfter": ".types",
    "WindowBefore": ".types",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "Attendee",
    "AttendeeRole",
    "AttendeeStatus",
    "Calendar",
    "CalendarConsistency",
    "CalendarEvent",
    "CalendarEventId",
    "CalendarEventKind",
    "CalendarEventMutationResponse",
    "CalendarEventSource",
    "CalendarEventStatus",
    "CalendarLimit",
    "CreateCalendarEventRequest",
    "DeleteCalendarEventResponse",
    "DeletionId",
    "DurationMode",
    "EventExpiredError",
    "ForbiddenError",
    "IanaTimezone",
    "IncludeOverlapping",
    "InstanceMutationMode",
    "ListCalendarEventsResponse",
    "OperationId",
    "PayloadTooLargeError",
    "PreconditionFailedError",
    "PreconditionFailedErrorResponse",
    "RateLimitError",
    "Recurrence",
    "RecurrenceDate",
    "RecurrenceInput",
    "RecurrencePeriod",
    "ResourceRevision",
    "RespondCalendarEventRequest",
    "RespondStatus",
    "UpdateCalendarEventRequest",
    "UpdateCalendarRequest",
    "WallTime",
    "WindowAfter",
    "WindowBefore",
]
