# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        ClientId,
        CreateInboxWebhookRequest,
        CreatePodWebhookRequest,
        CreateWebhookEventTypes,
        CreateWebhookRequest,
        ListWebhooksResponse,
        UpdateInboxWebhookRequest,
        UpdatePodWebhookRequest,
        UpdateWebhookEventTypes,
        UpdateWebhookHeadersRequest,
        UpdateWebhookRequest,
        Url,
        Webhook,
        WebhookHeaderNamesResponse,
        WebhookHeaders,
        WebhookId,
    )
    from . import events, polling
    from .events import SvixId, SvixSignature, SvixTimestamp
    from .polling import (
        CreateInboxPollingWebhookRequest,
        CreatePodPollingWebhookRequest,
        CreatePollingWebhookRequest,
        CreatePollingWebhookResponse,
        ListPollingWebhooksResponse,
        PollingClientId,
        PollingToken,
        PollingWebhook,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "ClientId": ".types",
    "CreateInboxPollingWebhookRequest": ".polling",
    "CreateInboxWebhookRequest": ".types",
    "CreatePodPollingWebhookRequest": ".polling",
    "CreatePodWebhookRequest": ".types",
    "CreatePollingWebhookRequest": ".polling",
    "CreatePollingWebhookResponse": ".polling",
    "CreateWebhookEventTypes": ".types",
    "CreateWebhookRequest": ".types",
    "ListPollingWebhooksResponse": ".polling",
    "ListWebhooksResponse": ".types",
    "PollingClientId": ".polling",
    "PollingToken": ".polling",
    "PollingWebhook": ".polling",
    "SvixId": ".events",
    "SvixSignature": ".events",
    "SvixTimestamp": ".events",
    "UpdateInboxWebhookRequest": ".types",
    "UpdatePodWebhookRequest": ".types",
    "UpdateWebhookEventTypes": ".types",
    "UpdateWebhookHeadersRequest": ".types",
    "UpdateWebhookRequest": ".types",
    "Url": ".types",
    "Webhook": ".types",
    "WebhookHeaderNamesResponse": ".types",
    "WebhookHeaders": ".types",
    "WebhookId": ".types",
    "events": ".events",
    "polling": ".polling",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ClientId",
    "CreateInboxPollingWebhookRequest",
    "CreateInboxWebhookRequest",
    "CreatePodPollingWebhookRequest",
    "CreatePodWebhookRequest",
    "CreatePollingWebhookRequest",
    "CreatePollingWebhookResponse",
    "CreateWebhookEventTypes",
    "CreateWebhookRequest",
    "ListPollingWebhooksResponse",
    "ListWebhooksResponse",
    "PollingClientId",
    "PollingToken",
    "PollingWebhook",
    "SvixId",
    "SvixSignature",
    "SvixTimestamp",
    "UpdateInboxWebhookRequest",
    "UpdatePodWebhookRequest",
    "UpdateWebhookEventTypes",
    "UpdateWebhookHeadersRequest",
    "UpdateWebhookRequest",
    "Url",
    "Webhook",
    "WebhookHeaderNamesResponse",
    "WebhookHeaders",
    "WebhookId",
    "events",
    "polling",
]
