# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..events.types.inbox_ids import InboxIds
from ..events.types.pod_ids import PodIds
from ..types.ascending import Ascending
from ..types.limit import Limit
from ..types.page_token import PageToken
from .raw_client import AsyncRawWebhooksClient, RawWebhooksClient
from .types.client_id import ClientId
from .types.create_webhook_event_types import CreateWebhookEventTypes
from .types.list_webhooks_response import ListWebhooksResponse
from .types.update_webhook_event_types import UpdateWebhookEventTypes
from .types.url import Url
from .types.webhook import Webhook
from .types.webhook_header_names_response import WebhookHeaderNamesResponse
from .types.webhook_headers import WebhookHeaders
from .types.webhook_id import WebhookId

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class WebhooksClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawWebhooksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawWebhooksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawWebhooksClient
        """
        return self._raw_client

    def list(
        self,
        *,
        limit: typing.Optional[Limit] = None,
        page_token: typing.Optional[PageToken] = None,
        ascending: typing.Optional[Ascending] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListWebhooksResponse:
        """
        **CLI:**
        ```bash
        agentmail webhooks list
        ```

        Parameters
        ----------
        limit : typing.Optional[Limit]

        page_token : typing.Optional[PageToken]

        ascending : typing.Optional[Ascending]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListWebhooksResponse

        Examples
        --------
        from agentmail import AgentMail

        client = AgentMail(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.list()
        """
        _response = self._raw_client.list(
            limit=limit, page_token=page_token, ascending=ascending, request_options=request_options
        )
        return _response.data

    def get(self, webhook_id: WebhookId, *, request_options: typing.Optional[RequestOptions] = None) -> Webhook:
        """
        **CLI:**
        ```bash
        agentmail webhooks get --webhook-id <webhook_id>
        ```

        Parameters
        ----------
        webhook_id : WebhookId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Webhook

        Examples
        --------
        from agentmail import AgentMail

        client = AgentMail(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.get(
            webhook_id="webhook_id",
        )
        """
        _response = self._raw_client.get(webhook_id, request_options=request_options)
        return _response.data

    def get_headers(
        self, webhook_id: WebhookId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> WebhookHeaderNamesResponse:
        """
        List the names of custom HTTP headers included with deliveries to this webhook. Header values are
        write-only and are never returned.

        Parameters
        ----------
        webhook_id : WebhookId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhookHeaderNamesResponse

        Examples
        --------
        from agentmail import AgentMail

        client = AgentMail(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.get_headers(
            webhook_id="webhook_id",
        )
        """
        _response = self._raw_client.get_headers(webhook_id, request_options=request_options)
        return _response.data

    def create(
        self,
        *,
        url: Url,
        event_types: CreateWebhookEventTypes,
        pod_ids: typing.Optional[PodIds] = OMIT,
        inbox_ids: typing.Optional[InboxIds] = OMIT,
        client_id: typing.Optional[ClientId] = OMIT,
        headers: typing.Optional[WebhookHeaders] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Webhook:
        """
        **CLI:**
        ```bash
        agentmail webhooks create --url https://example.com/webhook --event-type message.received
        ```

        Parameters
        ----------
        url : Url

        event_types : CreateWebhookEventTypes

        pod_ids : typing.Optional[PodIds]

        inbox_ids : typing.Optional[InboxIds]

        client_id : typing.Optional[ClientId]

        headers : typing.Optional[WebhookHeaders]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Webhook

        Examples
        --------
        from agentmail import AgentMail

        client = AgentMail(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.create(
            url="url",
            event_types=["message.received", "message.received"],
        )
        """
        _response = self._raw_client.create(
            url=url,
            event_types=event_types,
            pod_ids=pod_ids,
            inbox_ids=inbox_ids,
            client_id=client_id,
            headers=headers,
            request_options=request_options,
        )
        return _response.data

    def update(
        self,
        webhook_id: WebhookId,
        *,
        add_pod_ids: typing.Optional[PodIds] = OMIT,
        remove_pod_ids: typing.Optional[PodIds] = OMIT,
        add_inbox_ids: typing.Optional[InboxIds] = OMIT,
        remove_inbox_ids: typing.Optional[InboxIds] = OMIT,
        event_types: typing.Optional[UpdateWebhookEventTypes] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Webhook:
        """
        Update inbox or pod subscriptions, or replace the webhook's `event_types` in full when you pass a
        non-empty `event_types` array (see request field docs). Inbox and pod changes use add/remove lists.

        **CLI:**
        ```bash
        agentmail webhooks update --webhook-id <webhook_id> --add-inbox-id <inbox_id>
        ```

        Parameters
        ----------
        webhook_id : WebhookId

        add_pod_ids : typing.Optional[PodIds]
            Pod IDs to subscribe to the webhook.

        remove_pod_ids : typing.Optional[PodIds]
            Pod IDs to unsubscribe from the webhook.

        add_inbox_ids : typing.Optional[InboxIds]
            Inbox IDs to subscribe to the webhook.

        remove_inbox_ids : typing.Optional[InboxIds]
            Inbox IDs to unsubscribe from the webhook.

        event_types : typing.Optional[UpdateWebhookEventTypes]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Webhook

        Examples
        --------
        from agentmail import AgentMail

        client = AgentMail(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.update(
            webhook_id="webhook_id",
        )
        """
        _response = self._raw_client.update(
            webhook_id,
            add_pod_ids=add_pod_ids,
            remove_pod_ids=remove_pod_ids,
            add_inbox_ids=add_inbox_ids,
            remove_inbox_ids=remove_inbox_ids,
            event_types=event_types,
            request_options=request_options,
        )
        return _response.data

    def update_headers(
        self,
        webhook_id: WebhookId,
        *,
        headers: typing.Optional[WebhookHeaders] = OMIT,
        remove_headers: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Atomically set, replace, or remove custom HTTP headers included with deliveries to this webhook.
        Header values remain write-only.

        Parameters
        ----------
        webhook_id : WebhookId

        headers : typing.Optional[WebhookHeaders]

        remove_headers : typing.Optional[typing.Sequence[str]]
            Names of custom delivery headers to remove.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from agentmail import AgentMail

        client = AgentMail(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.update_headers(
            webhook_id="webhook_id",
        )
        """
        _response = self._raw_client.update_headers(
            webhook_id, headers=headers, remove_headers=remove_headers, request_options=request_options
        )
        return _response.data

    def delete(self, webhook_id: WebhookId, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        **CLI:**
        ```bash
        agentmail webhooks delete --webhook-id <webhook_id>
        ```

        Parameters
        ----------
        webhook_id : WebhookId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from agentmail import AgentMail

        client = AgentMail(
            api_key="YOUR_API_KEY",
        )
        client.webhooks.delete(
            webhook_id="webhook_id",
        )
        """
        _response = self._raw_client.delete(webhook_id, request_options=request_options)
        return _response.data


class AsyncWebhooksClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawWebhooksClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawWebhooksClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawWebhooksClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        limit: typing.Optional[Limit] = None,
        page_token: typing.Optional[PageToken] = None,
        ascending: typing.Optional[Ascending] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListWebhooksResponse:
        """
        **CLI:**
        ```bash
        agentmail webhooks list
        ```

        Parameters
        ----------
        limit : typing.Optional[Limit]

        page_token : typing.Optional[PageToken]

        ascending : typing.Optional[Ascending]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListWebhooksResponse

        Examples
        --------
        import asyncio

        from agentmail import AsyncAgentMail

        client = AsyncAgentMail(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.list()


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            limit=limit, page_token=page_token, ascending=ascending, request_options=request_options
        )
        return _response.data

    async def get(self, webhook_id: WebhookId, *, request_options: typing.Optional[RequestOptions] = None) -> Webhook:
        """
        **CLI:**
        ```bash
        agentmail webhooks get --webhook-id <webhook_id>
        ```

        Parameters
        ----------
        webhook_id : WebhookId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Webhook

        Examples
        --------
        import asyncio

        from agentmail import AsyncAgentMail

        client = AsyncAgentMail(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.get(
                webhook_id="webhook_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(webhook_id, request_options=request_options)
        return _response.data

    async def get_headers(
        self, webhook_id: WebhookId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> WebhookHeaderNamesResponse:
        """
        List the names of custom HTTP headers included with deliveries to this webhook. Header values are
        write-only and are never returned.

        Parameters
        ----------
        webhook_id : WebhookId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        WebhookHeaderNamesResponse

        Examples
        --------
        import asyncio

        from agentmail import AsyncAgentMail

        client = AsyncAgentMail(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.get_headers(
                webhook_id="webhook_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_headers(webhook_id, request_options=request_options)
        return _response.data

    async def create(
        self,
        *,
        url: Url,
        event_types: CreateWebhookEventTypes,
        pod_ids: typing.Optional[PodIds] = OMIT,
        inbox_ids: typing.Optional[InboxIds] = OMIT,
        client_id: typing.Optional[ClientId] = OMIT,
        headers: typing.Optional[WebhookHeaders] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Webhook:
        """
        **CLI:**
        ```bash
        agentmail webhooks create --url https://example.com/webhook --event-type message.received
        ```

        Parameters
        ----------
        url : Url

        event_types : CreateWebhookEventTypes

        pod_ids : typing.Optional[PodIds]

        inbox_ids : typing.Optional[InboxIds]

        client_id : typing.Optional[ClientId]

        headers : typing.Optional[WebhookHeaders]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Webhook

        Examples
        --------
        import asyncio

        from agentmail import AsyncAgentMail

        client = AsyncAgentMail(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.create(
                url="url",
                event_types=["message.received", "message.received"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            url=url,
            event_types=event_types,
            pod_ids=pod_ids,
            inbox_ids=inbox_ids,
            client_id=client_id,
            headers=headers,
            request_options=request_options,
        )
        return _response.data

    async def update(
        self,
        webhook_id: WebhookId,
        *,
        add_pod_ids: typing.Optional[PodIds] = OMIT,
        remove_pod_ids: typing.Optional[PodIds] = OMIT,
        add_inbox_ids: typing.Optional[InboxIds] = OMIT,
        remove_inbox_ids: typing.Optional[InboxIds] = OMIT,
        event_types: typing.Optional[UpdateWebhookEventTypes] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Webhook:
        """
        Update inbox or pod subscriptions, or replace the webhook's `event_types` in full when you pass a
        non-empty `event_types` array (see request field docs). Inbox and pod changes use add/remove lists.

        **CLI:**
        ```bash
        agentmail webhooks update --webhook-id <webhook_id> --add-inbox-id <inbox_id>
        ```

        Parameters
        ----------
        webhook_id : WebhookId

        add_pod_ids : typing.Optional[PodIds]
            Pod IDs to subscribe to the webhook.

        remove_pod_ids : typing.Optional[PodIds]
            Pod IDs to unsubscribe from the webhook.

        add_inbox_ids : typing.Optional[InboxIds]
            Inbox IDs to subscribe to the webhook.

        remove_inbox_ids : typing.Optional[InboxIds]
            Inbox IDs to unsubscribe from the webhook.

        event_types : typing.Optional[UpdateWebhookEventTypes]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Webhook

        Examples
        --------
        import asyncio

        from agentmail import AsyncAgentMail

        client = AsyncAgentMail(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.update(
                webhook_id="webhook_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            webhook_id,
            add_pod_ids=add_pod_ids,
            remove_pod_ids=remove_pod_ids,
            add_inbox_ids=add_inbox_ids,
            remove_inbox_ids=remove_inbox_ids,
            event_types=event_types,
            request_options=request_options,
        )
        return _response.data

    async def update_headers(
        self,
        webhook_id: WebhookId,
        *,
        headers: typing.Optional[WebhookHeaders] = OMIT,
        remove_headers: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> None:
        """
        Atomically set, replace, or remove custom HTTP headers included with deliveries to this webhook.
        Header values remain write-only.

        Parameters
        ----------
        webhook_id : WebhookId

        headers : typing.Optional[WebhookHeaders]

        remove_headers : typing.Optional[typing.Sequence[str]]
            Names of custom delivery headers to remove.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from agentmail import AsyncAgentMail

        client = AsyncAgentMail(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.update_headers(
                webhook_id="webhook_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_headers(
            webhook_id, headers=headers, remove_headers=remove_headers, request_options=request_options
        )
        return _response.data

    async def delete(self, webhook_id: WebhookId, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        **CLI:**
        ```bash
        agentmail webhooks delete --webhook-id <webhook_id>
        ```

        Parameters
        ----------
        webhook_id : WebhookId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from agentmail import AsyncAgentMail

        client = AsyncAgentMail(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.webhooks.delete(
                webhook_id="webhook_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(webhook_id, request_options=request_options)
        return _response.data
