# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .descending import Descending
    from .end import End
    from .metric_bucket import MetricBucket
    from .metric_event_type import MetricEventType
    from .metric_event_types import MetricEventTypes
    from .metric_limit import MetricLimit
    from .period import Period
    from .query_metrics_response import QueryMetricsResponse
    from .query_rates_response import QueryRatesResponse
    from .query_usage_response import QueryUsageResponse
    from .rate_period import RatePeriod
    from .rate_point import RatePoint
    from .rate_type import RateType
    from .rate_types import RateTypes
    from .start import Start
    from .usage_point import UsagePoint
    from .usage_type import UsageType
    from .usage_types import UsageTypes
    from .window import Window
_dynamic_imports: typing.Dict[str, str] = {
    "Descending": ".descending",
    "End": ".end",
    "MetricBucket": ".metric_bucket",
    "MetricEventType": ".metric_event_type",
    "MetricEventTypes": ".metric_event_types",
    "MetricLimit": ".metric_limit",
    "Period": ".period",
    "QueryMetricsResponse": ".query_metrics_response",
    "QueryRatesResponse": ".query_rates_response",
    "QueryUsageResponse": ".query_usage_response",
    "RatePeriod": ".rate_period",
    "RatePoint": ".rate_point",
    "RateType": ".rate_type",
    "RateTypes": ".rate_types",
    "Start": ".start",
    "UsagePoint": ".usage_point",
    "UsageType": ".usage_type",
    "UsageTypes": ".usage_types",
    "Window": ".window",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "Descending",
    "End",
    "MetricBucket",
    "MetricEventType",
    "MetricEventTypes",
    "MetricLimit",
    "Period",
    "QueryMetricsResponse",
    "QueryRatesResponse",
    "QueryUsageResponse",
    "RatePeriod",
    "RatePoint",
    "RateType",
    "RateTypes",
    "Start",
    "UsagePoint",
    "UsageType",
    "UsageTypes",
    "Window",
]
