# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel


class RatePoint(UncheckedBaseModel):
    timestamp: dt.datetime = pydantic.Field()
    """
    End of the window the point covers; the window is the `window` seconds before it.
    """

    rate: typing.Optional[float] = pydantic.Field(default=None)
    """
    Bounced or complained messages divided by messages sent over the
    window, as a fraction (0.05 is 5%). Null when nothing was sent in
    the window.
    """

    sent: int = pydantic.Field()
    """
    Messages sent in the window, counted per recipient.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
