# This file was auto-generated by Fern from our API Definition.

import typing

UsageType = typing.Union[
    typing.Literal["storage_bytes", "message_count", "thread_count", "inbox_count", "pod_count", "domain_count"],
    typing.Any,
]
