# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...calendar.types.calendar_event import CalendarEvent
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from ...inboxes.types.inbox_id import InboxId
from .event_id import EventId


class CalendarEventCreatedEvent(UncheckedBaseModel):
    """
    An event was created, through the API or from an invitation the inbox received. Also sent when
    one date of a recurring event is edited for the first time; `calendar_event` is then that date.
    """

    type: typing.Literal["event"] = "event"
    event_type: typing.Literal["calendar.event.created"] = "calendar.event.created"
    event_id: EventId = pydantic.Field()
    """
    Equals the `operation_id` returned by the request that made the change.
    """

    inbox_id: InboxId
    calendar_event: CalendarEvent

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
