# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...calendar.types.attendee import Attendee
from ...calendar.types.calendar_event_status import CalendarEventStatus
from ...calendar.types.duration_mode import DurationMode
from ...calendar.types.iana_timezone import IanaTimezone
from ...calendar.types.recurrence import Recurrence
from ...calendar.types.wall_time import WallTime
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel


class CalendarEventPrevious(UncheckedBaseModel):
    """
    The values that a `calendar.event.updated` change replaced, for the fields it changed. Only
    changed fields appear; a field that had no value before the change is absent.
    """

    title: typing.Optional[str] = None
    description: typing.Optional[str] = None
    location: typing.Optional[str] = None
    metadata: typing.Optional[typing.Any] = None
    status: typing.Optional[CalendarEventStatus] = None
    all_day: typing.Optional[bool] = None
    start: typing.Optional[WallTime] = None
    end: typing.Optional[WallTime] = None
    timezone: typing.Optional[IanaTimezone] = None
    duration_mode: typing.Optional[DurationMode] = None
    recurrence: typing.Optional[Recurrence] = None
    attendees: typing.Optional[typing.List[Attendee]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
