# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ...calendar.types.calendar_event import CalendarEvent
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from ...inboxes.types.inbox_id import InboxId
from .event_id import EventId


class CalendarEventStartingEvent(UncheckedBaseModel):
    """
    An event, or one date of a recurring event, has started. Usually sent within a minute after
    `scheduled_at`. If a date is first picked up after it has already ended and more than 5
    minutes after its start (for example, an event created entirely in the past), neither its
    `calendar.event.starting` nor its `calendar.event.ending` is sent. Retries carry the same
    `event_id` and an identical body.
    """

    type: typing.Literal["event"] = "event"
    event_type: typing.Literal["calendar.event.starting"] = "calendar.event.starting"
    event_id: EventId = pydantic.Field()
    """
    Stable for this date and boundary. Use it to deduplicate deliveries.
    """

    inbox_id: InboxId
    calendar_event: CalendarEvent = pydantic.Field()
    """
    The event or date as it stood when the boundary was first processed.
    """

    scheduled_at: dt.datetime = pydantic.Field()
    """
    The start this webhook is for (the event's `start_at`).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
