# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...calendar.types.calendar_event import CalendarEvent
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from ...inboxes.types.inbox_id import InboxId
from .calendar_event_previous import CalendarEventPrevious
from .event_id import EventId


class CalendarEventUpdatedEvent(UncheckedBaseModel):
    """
    An event, or one or more dates of a recurring event, changed. `calendar_event` is the event
    (or the date) after the change. Cancelling dates with a delete on a dated ID also sends this
    event, with the cancelled date as `calendar_event`.
    """

    type: typing.Literal["event"] = "event"
    event_type: typing.Literal["calendar.event.updated"] = "calendar.event.updated"
    event_id: EventId = pydantic.Field()
    """
    Equals the `operation_id` returned by the request that made the change.
    """

    inbox_id: InboxId
    calendar_event: CalendarEvent
    previous: typing.Optional[CalendarEventPrevious] = pydantic.Field(default=None)
    """
    For changes to a one-off or series event, the prior values of the fields that changed.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
