# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...calendar.types.calendar_event import CalendarEvent
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from ...inboxes.types.inbox_id import InboxId
from .event_id import EventId


class CalendarEventRespondedEvent(UncheckedBaseModel):
    """
    An attendee's response changed: the inbox responded with the respond endpoint, or an attendee
    replied by email to an invitation the inbox sent. `calendar_event.attendees` holds the new
    statuses.
    """

    type: typing.Literal["event"] = "event"
    event_type: typing.Literal["calendar.event.responded"] = "calendar.event.responded"
    event_id: EventId
    inbox_id: InboxId
    calendar_event: CalendarEvent

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
