# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .attendee import Attendee
    from .attendee_role import AttendeeRole
    from .attendee_status import AttendeeStatus
    from .calendar import Calendar
    from .calendar_consistency import CalendarConsistency
    from .calendar_event import CalendarEvent
    from .calendar_event_id import CalendarEventId
    from .calendar_event_kind import CalendarEventKind
    from .calendar_event_mutation_response import CalendarEventMutationResponse
    from .calendar_event_source import CalendarEventSource
    from .calendar_event_status import CalendarEventStatus
    from .calendar_limit import CalendarLimit
    from .create_calendar_event_request import CreateCalendarEventRequest
    from .delete_calendar_event_response import DeleteCalendarEventResponse
    from .deletion_id import DeletionId
    from .duration_mode import DurationMode
    from .iana_timezone import IanaTimezone
    from .include_overlapping import IncludeOverlapping
    from .instance_mutation_mode import InstanceMutationMode
    from .list_calendar_events_response import ListCalendarEventsResponse
    from .operation_id import OperationId
    from .precondition_failed_error_response import PreconditionFailedErrorResponse
    from .recurrence import Recurrence
    from .recurrence_date import RecurrenceDate
    from .recurrence_input import RecurrenceInput
    from .recurrence_period import RecurrencePeriod
    from .resource_revision import ResourceRevision
    from .respond_calendar_event_request import RespondCalendarEventRequest
    from .respond_status import RespondStatus
    from .update_calendar_event_request import UpdateCalendarEventRequest
    from .update_calendar_request import UpdateCalendarRequest
    from .wall_time import WallTime
    from .window_after import WindowAfter
    from .window_before import WindowBefore
_dynamic_imports: typing.Dict[str, str] = {
    "Attendee": ".attendee",
    "AttendeeRole": ".attendee_role",
    "AttendeeStatus": ".attendee_status",
    "Calendar": ".calendar",
    "CalendarConsistency": ".calendar_consistency",
    "CalendarEvent": ".calendar_event",
    "CalendarEventId": ".calendar_event_id",
    "CalendarEventKind": ".calendar_event_kind",
    "CalendarEventMutationResponse": ".calendar_event_mutation_response",
    "CalendarEventSource": ".calendar_event_source",
    "CalendarEventStatus": ".calendar_event_status",
    "CalendarLimit": ".calendar_limit",
    "CreateCalendarEventRequest": ".create_calendar_event_request",
    "DeleteCalendarEventResponse": ".delete_calendar_event_response",
    "DeletionId": ".deletion_id",
    "DurationMode": ".duration_mode",
    "IanaTimezone": ".iana_timezone",
    "IncludeOverlapping": ".include_overlapping",
    "InstanceMutationMode": ".instance_mutation_mode",
    "ListCalendarEventsResponse": ".list_calendar_events_response",
    "OperationId": ".operation_id",
    "PreconditionFailedErrorResponse": ".precondition_failed_error_response",
    "Recurrence": ".recurrence",
    "RecurrenceDate": ".recurrence_date",
    "RecurrenceInput": ".recurrence_input",
    "RecurrencePeriod": ".recurrence_period",
    "ResourceRevision": ".resource_revision",
    "RespondCalendarEventRequest": ".respond_calendar_event_request",
    "RespondStatus": ".respond_status",
    "UpdateCalendarEventRequest": ".update_calendar_event_request",
    "UpdateCalendarRequest": ".update_calendar_request",
    "WallTime": ".wall_time",
    "WindowAfter": ".window_after",
    "WindowBefore": ".window_before",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "Attendee",
    "AttendeeRole",
    "AttendeeStatus",
    "Calendar",
    "CalendarConsistency",
    "CalendarEvent",
    "CalendarEventId",
    "CalendarEventKind",
    "CalendarEventMutationResponse",
    "CalendarEventSource",
    "CalendarEventStatus",
    "CalendarLimit",
    "CreateCalendarEventRequest",
    "DeleteCalendarEventResponse",
    "DeletionId",
    "DurationMode",
    "IanaTimezone",
    "IncludeOverlapping",
    "InstanceMutationMode",
    "ListCalendarEventsResponse",
    "OperationId",
    "PreconditionFailedErrorResponse",
    "Recurrence",
    "RecurrenceDate",
    "RecurrenceInput",
    "RecurrencePeriod",
    "ResourceRevision",
    "RespondCalendarEventRequest",
    "RespondStatus",
    "UpdateCalendarEventRequest",
    "UpdateCalendarRequest",
    "WallTime",
    "WindowAfter",
    "WindowBefore",
]
