# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from ...inboxes.types.inbox_id import InboxId
from .iana_timezone import IanaTimezone


class Calendar(UncheckedBaseModel):
    """
    An inbox's calendar. Every inbox has exactly one calendar; it exists from the moment the inbox
    does and is deleted with it.
    """

    inbox_id: InboxId
    timezone: IanaTimezone = pydantic.Field()
    """
    Default time zone for events created without a `timezone`. Defaults to `UTC`. Changing it
    does not move existing events.
    """

    event_count: int = pydantic.Field()
    """
    Number of one-off and recurring events on the calendar. Each recurring event counts once.
    """

    created_at: dt.datetime = pydantic.Field()
    """
    Time at which the calendar was created. The calendar exists from the moment the inbox does, so this is the inbox's creation time.
    """

    updated_at: dt.datetime = pydantic.Field()
    """
    Time at which the calendar was last updated.
    """

    etag: str = pydantic.Field()
    """
    The calendar's current version, also sent as the `ETag` response header. Send it in
    `If-Match` to make an update conditional.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
