# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from ...types.count import Count
from ...types.limit import Limit
from ...types.page_token import PageToken
from .calendar_event import CalendarEvent


class ListCalendarEventsResponse(UncheckedBaseModel):
    count: Count
    limit: Limit
    next_page_token: typing.Optional[PageToken] = None
    events: typing.List[CalendarEvent] = pydantic.Field()
    """
    On List Events, ordered by `updated_at` descending. On Get Agenda and List Event Instances,
    ordered by `start_at` ascending.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
