# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from ...types.error_code import ErrorCode
from ...types.error_docs import ErrorDocs
from ...types.error_fix import ErrorFix
from ...types.error_message import ErrorMessage
from ...types.error_name import ErrorName


class PreconditionFailedErrorResponse(UncheckedBaseModel):
    name: ErrorName
    code: typing.Optional[ErrorCode] = None
    message: ErrorMessage
    current_revision: typing.Optional[int] = pydantic.Field(default=None)
    """
    The resource's current revision.
    """

    fix: typing.Optional[ErrorFix] = None
    docs: typing.Optional[ErrorDocs] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
