# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .recurrence_date import RecurrenceDate
from .wall_time import WallTime


class Recurrence(UncheckedBaseModel):
    """
    The recurrence of a series, as stored.
    """

    rule: str = pydantic.Field()
    """
    Normalized RRULE body, without the `RRULE:` prefix.
    """

    exdates: typing.Optional[typing.List[WallTime]] = None
    rdates: typing.Optional[typing.List[RecurrenceDate]] = None
    truncate_before: typing.Optional[WallTime] = pydantic.Field(default=None)
    """
    Set when the series was ended with a `mode=future` delete: no date starting at or after
    this wall-clock time occurs.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
