# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .recurrence_date import RecurrenceDate
from .wall_time import WallTime


class RecurrenceInput(UncheckedBaseModel):
    """
    Repeats the event. `rule` is an RFC 5545 RRULE, evaluated in the event's `timezone` from the
    event's `start`. Each date keeps its wall-clock time across daylight-saving changes.
    """

    rule: str = pydantic.Field()
    """
    RFC 5545 RRULE body, with or without the `RRULE:` prefix, for example
    `FREQ=WEEKLY;BYDAY=MO,WE,FR` or `FREQ=MONTHLY;BYDAY=-1FR;COUNT=12`. Supported parts: `FREQ`,
    `INTERVAL` (1 to 366), `COUNT` (1 to 10,000), `UNTIL` (`YYYYMMDD` for all-day events,
    `YYYYMMDDTHHMMSSZ` for timed events),
    `WKST`, `BYMONTH`, `BYWEEKNO`, `BYYEARDAY`, `BYMONTHDAY`, `BYDAY`, `BYHOUR`, `BYMINUTE`,
    `BYSECOND` and `BYSETPOS`. `COUNT` and `UNTIL` are mutually exclusive. The rule is stored in
    a normalized form, so a response can differ textually from what you sent. At most 512
    characters after normalization.
    """

    exdates: typing.Optional[typing.List[WallTime]] = pydantic.Field(default=None)
    """
    Dates to skip, matching the original start of a date: `YYYY-MM-DDTHH:mm:ss` for timed events,
    `YYYY-MM-DD` for all-day events. At most 366.
    """

    rdates: typing.Optional[typing.List[RecurrenceDate]] = pydantic.Field(default=None)
    """
    Extra dates to add. Timed events take date-times or periods; all-day events take dates. At
    most 100.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
