# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .wall_time import WallTime


class RecurrencePeriod(UncheckedBaseModel):
    """
    An extra date (RDATE) given as a period. Specify exactly one of `end` or `duration`.
    """

    start: WallTime
    end: typing.Optional[WallTime] = None
    duration: typing.Optional[str] = pydantic.Field(default=None)
    """
    ISO 8601 duration, for example `PT30M`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
