# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .attendee import Attendee
from .calendar_event_status import CalendarEventStatus
from .duration_mode import DurationMode
from .iana_timezone import IanaTimezone
from .recurrence_input import RecurrenceInput
from .wall_time import WallTime


class UpdateCalendarEventRequest(UncheckedBaseModel):
    """
    Send only the fields to change. Fields set to `null` are cleared. At least one field is required.
    `all_day`, `timezone` and `recurrence` can only be changed on a one-off or series UUID, not on a
    dated event ID.
    """

    title: typing.Optional[str] = None
    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Set to `null` to clear.
    """

    location: typing.Optional[str] = pydantic.Field(default=None)
    """
    Set to `null` to clear.
    """

    metadata: typing.Optional[typing.Any] = pydantic.Field(default=None)
    """
    Replaces the metadata (any JSON value, usually an object). Set to `null` to clear.
    """

    status: typing.Optional[CalendarEventStatus] = None
    all_day: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Changing `all_day` requires `start`, `end` and `timezone` in the same request. Not accepted for dated event IDs.
    """

    start: typing.Optional[WallTime] = pydantic.Field(default=None)
    """
    New start. For a one-off or series UUID, send it together with `end`. Not accepted with `mode=future`.
    """

    end: typing.Optional[WallTime] = pydantic.Field(default=None)
    """
    New end. For a one-off or series UUID, send it together with `start`. A dated ID accepts `end` alone.
    """

    timezone: typing.Optional[IanaTimezone] = pydantic.Field(default=None)
    """
    New time zone. Not accepted for dated event IDs.
    """

    duration_mode: typing.Optional[DurationMode] = None
    recurrence: typing.Optional[RecurrenceInput] = pydantic.Field(default=None)
    """
    Replaces the recurrence. Set to `null` to turn a series into a one-off event (only when no
    date of it has been edited). Not accepted for dated event IDs.
    """

    attendees: typing.Optional[typing.List[Attendee]] = pydantic.Field(default=None)
    """
    Replaces the attendee list.
    """

    send_invites: typing.Optional[bool] = pydantic.Field(default=None)
    """
    When `true`, emails the updated invitation to every attendee. Only the organizer (an `api`
    event) can send. Defaults to `false`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
