# This file was auto-generated by Fern from our API Definition.

import typing

from .bearer_api_key import BearerApiKey
from .public_key_credential import PublicKeyCredential

ApiKey = typing.Union[BearerApiKey, PublicKeyCredential]
