# This file was auto-generated by Fern from our API Definition.

import typing
import uuid

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel


class BrowserLifecycleCredentialActor(UncheckedBaseModel):
    credential_id: uuid.UUID
    authorizing_api_key_id: uuid.UUID

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
