# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing
import uuid

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel, UnionMetadata


class BrowserLifecycleActor_ApiKey(UncheckedBaseModel):
    type: typing.Literal["api_key"] = "api_key"
    api_key_id: uuid.UUID

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class BrowserLifecycleActor_BrowserCredential(UncheckedBaseModel):
    type: typing.Literal["browser_credential"] = "browser_credential"
    credential_id: uuid.UUID
    authorizing_api_key_id: uuid.UUID

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


BrowserLifecycleActor = typing_extensions.Annotated[
    typing.Union[BrowserLifecycleActor_ApiKey, BrowserLifecycleActor_BrowserCredential],
    UnionMetadata(discriminant="type"),
]
