# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing
import uuid

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .browser_credential_creator import BrowserCredentialCreator


class BrowserCredential(UncheckedBaseModel):
    """
    Owner-facing metadata for an active browser credential. Private key material never leaves the browser.
    """

    credential_id: uuid.UUID
    public_key_fingerprint_prefix: str
    organization_id: uuid.UUID
    pod_id: uuid.UUID
    inbox_id: str
    created_by: BrowserCredentialCreator
    created_at: dt.datetime
    expires_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
