# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing
import uuid

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .browser_consent_lifecycle_event_type import BrowserConsentLifecycleEventType
from .browser_lifecycle_actor import BrowserLifecycleActor


class BrowserConsentLifecycleEvent(UncheckedBaseModel):
    type: BrowserConsentLifecycleEventType
    trace_id: uuid.UUID
    event_id: uuid.UUID
    occurred_at: dt.datetime
    organization_id: uuid.UUID
    pod_id: uuid.UUID
    actor: BrowserLifecycleActor
    consent_id: str
    client_type: typing.Literal["closed"] = "closed"
    client_id: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
