# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing
import uuid

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel


class BrowserCredentialCreator(UncheckedBaseModel):
    kind: typing.Literal["bearer_api_key"] = "bearer_api_key"
    api_key_id: uuid.UUID = pydantic.Field()
    """
    Bearer API key that authorized creation of the browser credential.
    """

    created_at: dt.datetime = pydantic.Field()
    """
    Incarnation timestamp of the authorizing bearer API key.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
