# This file was auto-generated by Fern from our API Definition.

import typing

BrowserConsentLifecycleEventType = typing.Union[
    typing.Literal[
        "browser_consent_created", "browser_consent_updated", "browser_consent_reused", "browser_consent_revoked"
    ],
    typing.Any,
]
