# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing
import uuid

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .browser_enrollment_lifecycle_event_type import BrowserEnrollmentLifecycleEventType
from .browser_lifecycle_actor import BrowserLifecycleActor


class BrowserEnrollmentLifecycleEvent(UncheckedBaseModel):
    type: BrowserEnrollmentLifecycleEventType
    trace_id: uuid.UUID
    event_id: uuid.UUID
    occurred_at: dt.datetime
    organization_id: uuid.UUID
    pod_id: uuid.UUID
    actor: BrowserLifecycleActor
    enrollment_id: uuid.UUID
    credential_id: uuid.UUID

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
