# This file was auto-generated by Fern from our API Definition.

import typing

from .browser_consent_lifecycle_event import BrowserConsentLifecycleEvent
from .browser_enrollment_lifecycle_event import BrowserEnrollmentLifecycleEvent

BrowserLifecycleEvent = typing.Union[BrowserEnrollmentLifecycleEvent, BrowserConsentLifecycleEvent]
