# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .browser_enrollment_transaction_jti import BrowserEnrollmentTransactionJti


class CreateBrowserEnrollmentRequest(UncheckedBaseModel):
    """
    Attach a browser enrollment intent to one pending AgentID authorization
    transaction. The inbox is selected by the trusted path parameter, not an
    AgentID `login_hint`.
    """

    transaction_jti: BrowserEnrollmentTransactionJti

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
