# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .public_jwk import PublicJwk
from .public_key_scope import PublicKeyScope


class CreatePublicKeyRequest(UncheckedBaseModel):
    """
    Register only a public P-256 JWK. Credential type, `api_key_id`, sign-in
    eligibility, permissions, and generation are server-owned and are not
    request properties.
    """

    public_key: PublicJwk
    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Defaults to `AgentID key {first eight fingerprint characters}`.
    """

    scope: typing.Optional[PublicKeyScope] = pydantic.Field(default=None)
    """
    Omit to inherit the registering bearer key's exact scope. An explicit
    scope must be the caller's scope or a live descendant.
    """

    expires_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Future absolute expiry. Omit to inherit the registering bearer key's
    expiry. A child credential cannot outlive its creator.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
