# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from ...types.count import Count
from ...types.page_token import PageToken
from .public_key_credential import PublicKeyCredential


class ListPublicKeysResponse(UncheckedBaseModel):
    count: Count
    next_page_token: typing.Optional[PageToken] = None
    public_keys: typing.List[PublicKeyCredential] = pydantic.Field()
    """
    Public-key credentials only, ordered by creation time descending by default.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
