# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .public_jwk import PublicJwk


class PublicKeyMaterial(UncheckedBaseModel):
    """
    Registered public key material and its server-computed RFC 7638 thumbprint.
    """

    jwk: PublicJwk
    fingerprint: str = pydantic.Field()
    """
    RFC 7638 SHA-256 JWK thumbprint encoded as unpadded base64url.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
