# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing
import uuid

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel
from .name import Name
from .public_key_material import PublicKeyMaterial
from .public_key_scope import PublicKeyScope


class PublicKeyCredential(UncheckedBaseModel):
    """
    An AgentID sign-in credential. `type` and `api_key_id` are server-owned;
    use `api_key_id` as the JWS `kid`. This response never contains a bearer
    secret or private key.
    """

    api_key_id: uuid.UUID = pydantic.Field()
    """
    Server-generated credential ID. Store this value as the signing key's `kid`.
    """

    type: typing.Literal["public_key"] = pydantic.Field(default="public_key")
    """
    Server-owned credential discriminator. Callers cannot select or update it.
    """

    name: Name = pydantic.Field()
    """
    Human-readable credential name.
    """

    public_key: PublicKeyMaterial
    scope: PublicKeyScope
    expires_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Immutable absolute expiry. Omitted when the credential does not expire.
    """

    revoked_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Present when organization-wide revoke-all invalidated this credential generation.
    """

    created_at: dt.datetime
    updated_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
