# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing
import uuid

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel, UnionMetadata


class PublicKeyScope_Organization(UncheckedBaseModel):
    """
    The immutable scope in which a public-key credential can approve AgentID sign-in.
    """

    type: typing.Literal["organization"] = "organization"

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class PublicKeyScope_Pod(UncheckedBaseModel):
    """
    The immutable scope in which a public-key credential can approve AgentID sign-in.
    """

    type: typing.Literal["pod"] = "pod"
    id: uuid.UUID

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class PublicKeyScope_Inbox(UncheckedBaseModel):
    """
    The immutable scope in which a public-key credential can approve AgentID sign-in.
    """

    type: typing.Literal["inbox"] = "inbox"
    id: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


PublicKeyScope = typing_extensions.Annotated[
    typing.Union[PublicKeyScope_Organization, PublicKeyScope_Pod, PublicKeyScope_Inbox],
    UnionMetadata(discriminant="type"),
]
