# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from .api_key_mutable_fields import ApiKeyMutableFields


class UpdateApiKeyRequest(ApiKeyMutableFields):
    """
    Rename a credential or change its permissions. Key material, type,
    scope, and expiry are immutable.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
