# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.parse_error import ParsingError
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..core.unchecked_base_model import construct_type
from ..errors.not_found_error import NotFoundError
from ..errors.validation_error import ValidationError as errors_validation_error_ValidationError
from ..types.error_response import ErrorResponse
from ..types.limit import Limit
from ..types.page_token import PageToken
from ..types.validation_error_response import ValidationErrorResponse
from .errors.app_signup_limit_error import AppSignupLimitError
from .types.app import App
from .types.app_category import AppCategory
from .types.connect_accepted import ConnectAccepted
from .types.connect_app_body import ConnectAppBody
from .types.list_app_accounts_response import ListAppAccountsResponse
from .types.list_apps_response import ListAppsResponse
from .types.search_apps_response import SearchAppsResponse
from pydantic import ValidationError as pydantic_ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawAppsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list(
        self,
        *,
        limit: typing.Optional[Limit] = None,
        page_token: typing.Optional[PageToken] = None,
        category: typing.Optional[AppCategory] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ListAppsResponse]:
        """
        Lists apps, most popular first.

        Parameters
        ----------
        limit : typing.Optional[Limit]

        page_token : typing.Optional[PageToken]

        category : typing.Optional[AppCategory]
            Only apps in this category. A filtered page can hold fewer than `limit` apps while more remain, so page until `next_page_token` is absent. A `page_token` works only with the `category` it was returned for.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ListAppsResponse]
        """
        _response = self._client_wrapper.httpx_client.request(
            "v0/apps",
            base_url=self._client_wrapper.get_environment().http,
            method="GET",
            params={
                "limit": limit,
                "page_token": page_token,
                "category": category,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListAppsResponse,
                    construct_type(
                        type_=ListAppsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise errors_validation_error_ValidationError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorResponse,
                        construct_type(
                            type_=ValidationErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except pydantic_ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def search(
        self, *, q: str, limit: typing.Optional[Limit] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[SearchAppsResponse]:
        """
        Searches apps by name prefix.

        Parameters
        ----------
        q : str
            Name prefix to search for.

        limit : typing.Optional[Limit]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[SearchAppsResponse]
        """
        _response = self._client_wrapper.httpx_client.request(
            "v0/apps/search",
            base_url=self._client_wrapper.get_environment().http,
            method="GET",
            params={
                "q": q,
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SearchAppsResponse,
                    construct_type(
                        type_=SearchAppsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise errors_validation_error_ValidationError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorResponse,
                        construct_type(
                            type_=ValidationErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except pydantic_ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get(self, app_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[App]:
        """
        Gets one app by ID or slug. A catalog app returns its full entry.
        A registered app that the catalog does not list returns its ID and
        name only, without `updated_at`, so anyone holding its ID can still look
        it up; a slug finds catalog apps only. List Apps and Search Apps show
        catalog entries only.

        Parameters
        ----------
        app_id : str
            ID of app, or the `slug` of an app in the catalog. A slug ignores case, spaces and punctuation.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[App]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v0/apps/{jsonable_encoder(app_id)}",
            base_url=self._client_wrapper.get_environment().http,
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    App,
                    construct_type(
                        type_=App,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        construct_type(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except pydantic_ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def list_accounts(
        self,
        app_id: str,
        *,
        limit: typing.Optional[Limit] = None,
        page_token: typing.Optional[PageToken] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ListAppAccountsResponse]:
        """
        Lists accounts at one app, most recent sign-in first.

        Parameters
        ----------
        app_id : str
            ID of app, or the `slug` of an app in the catalog. A slug ignores case, spaces and punctuation.

        limit : typing.Optional[Limit]

        page_token : typing.Optional[PageToken]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ListAppAccountsResponse]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v0/apps/{jsonable_encoder(app_id)}/accounts",
            base_url=self._client_wrapper.get_environment().http,
            method="GET",
            params={
                "limit": limit,
                "page_token": page_token,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListAppAccountsResponse,
                    construct_type(
                        type_=ListAppAccountsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise errors_validation_error_ValidationError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorResponse,
                        construct_type(
                            type_=ValidationErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except pydantic_ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def connect(
        self,
        app_id: str,
        *,
        request: typing.Optional[ConnectAppBody] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ConnectAccepted]:
        """
        Starts signing an inbox in to an app. Returns a single-use `magic_url`,
        valid for five minutes, to open in the client that will hold the sign-in;
        the client enrolls as the inbox and continues to the app.
        An app in the catalog can be named by its `slug`, as in
        `POST /v0/apps/firecrawl/connect`.
        A `404` names the missing resource: `App` or `Inbox`.
        A `403` `AppSignupLimitError` means the app accepts no more sign-ups from
        your organization; sign in with an inbox that already has an account there.

        Parameters
        ----------
        app_id : str
            ID of app, or the `slug` of an app in the catalog. A slug ignores case, spaces and punctuation.

        request : typing.Optional[ConnectAppBody]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ConnectAccepted]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"v0/apps/{jsonable_encoder(app_id)}/connect",
            base_url=self._client_wrapper.get_environment().http,
            method="POST",
            json=convert_and_respect_annotation_metadata(object_=request, annotation=ConnectAppBody, direction="write"),
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ConnectAccepted,
                    construct_type(
                        type_=ConnectAccepted,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise errors_validation_error_ValidationError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorResponse,
                        construct_type(
                            type_=ValidationErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        construct_type(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise AppSignupLimitError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        construct_type(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except pydantic_ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawAppsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list(
        self,
        *,
        limit: typing.Optional[Limit] = None,
        page_token: typing.Optional[PageToken] = None,
        category: typing.Optional[AppCategory] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ListAppsResponse]:
        """
        Lists apps, most popular first.

        Parameters
        ----------
        limit : typing.Optional[Limit]

        page_token : typing.Optional[PageToken]

        category : typing.Optional[AppCategory]
            Only apps in this category. A filtered page can hold fewer than `limit` apps while more remain, so page until `next_page_token` is absent. A `page_token` works only with the `category` it was returned for.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ListAppsResponse]
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v0/apps",
            base_url=self._client_wrapper.get_environment().http,
            method="GET",
            params={
                "limit": limit,
                "page_token": page_token,
                "category": category,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListAppsResponse,
                    construct_type(
                        type_=ListAppsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise errors_validation_error_ValidationError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorResponse,
                        construct_type(
                            type_=ValidationErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except pydantic_ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def search(
        self, *, q: str, limit: typing.Optional[Limit] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[SearchAppsResponse]:
        """
        Searches apps by name prefix.

        Parameters
        ----------
        q : str
            Name prefix to search for.

        limit : typing.Optional[Limit]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[SearchAppsResponse]
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v0/apps/search",
            base_url=self._client_wrapper.get_environment().http,
            method="GET",
            params={
                "q": q,
                "limit": limit,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    SearchAppsResponse,
                    construct_type(
                        type_=SearchAppsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise errors_validation_error_ValidationError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorResponse,
                        construct_type(
                            type_=ValidationErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except pydantic_ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get(
        self, app_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[App]:
        """
        Gets one app by ID or slug. A catalog app returns its full entry.
        A registered app that the catalog does not list returns its ID and
        name only, without `updated_at`, so anyone holding its ID can still look
        it up; a slug finds catalog apps only. List Apps and Search Apps show
        catalog entries only.

        Parameters
        ----------
        app_id : str
            ID of app, or the `slug` of an app in the catalog. A slug ignores case, spaces and punctuation.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[App]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v0/apps/{jsonable_encoder(app_id)}",
            base_url=self._client_wrapper.get_environment().http,
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    App,
                    construct_type(
                        type_=App,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        construct_type(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except pydantic_ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def list_accounts(
        self,
        app_id: str,
        *,
        limit: typing.Optional[Limit] = None,
        page_token: typing.Optional[PageToken] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ListAppAccountsResponse]:
        """
        Lists accounts at one app, most recent sign-in first.

        Parameters
        ----------
        app_id : str
            ID of app, or the `slug` of an app in the catalog. A slug ignores case, spaces and punctuation.

        limit : typing.Optional[Limit]

        page_token : typing.Optional[PageToken]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ListAppAccountsResponse]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v0/apps/{jsonable_encoder(app_id)}/accounts",
            base_url=self._client_wrapper.get_environment().http,
            method="GET",
            params={
                "limit": limit,
                "page_token": page_token,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListAppAccountsResponse,
                    construct_type(
                        type_=ListAppAccountsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise errors_validation_error_ValidationError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorResponse,
                        construct_type(
                            type_=ValidationErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except pydantic_ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def connect(
        self,
        app_id: str,
        *,
        request: typing.Optional[ConnectAppBody] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ConnectAccepted]:
        """
        Starts signing an inbox in to an app. Returns a single-use `magic_url`,
        valid for five minutes, to open in the client that will hold the sign-in;
        the client enrolls as the inbox and continues to the app.
        An app in the catalog can be named by its `slug`, as in
        `POST /v0/apps/firecrawl/connect`.
        A `404` names the missing resource: `App` or `Inbox`.
        A `403` `AppSignupLimitError` means the app accepts no more sign-ups from
        your organization; sign in with an inbox that already has an account there.

        Parameters
        ----------
        app_id : str
            ID of app, or the `slug` of an app in the catalog. A slug ignores case, spaces and punctuation.

        request : typing.Optional[ConnectAppBody]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ConnectAccepted]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"v0/apps/{jsonable_encoder(app_id)}/connect",
            base_url=self._client_wrapper.get_environment().http,
            method="POST",
            json=convert_and_respect_annotation_metadata(object_=request, annotation=ConnectAppBody, direction="write"),
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ConnectAccepted,
                    construct_type(
                        type_=ConnectAccepted,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise errors_validation_error_ValidationError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ValidationErrorResponse,
                        construct_type(
                            type_=ValidationErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        construct_type(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise AppSignupLimitError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        ErrorResponse,
                        construct_type(
                            type_=ErrorResponse,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except pydantic_ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
