# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .connect_accepted import ConnectAccepted
    from .connect_inbox_id import ConnectInboxId
    from .connect_provider_body import ConnectProviderBody
    from .list_provider_accounts_response import ListProviderAccountsResponse
    from .list_providers_response import ListProvidersResponse
    from .magic_url import MagicUrl
    from .provider import Provider
    from .search_providers_response import SearchProvidersResponse
_dynamic_imports: typing.Dict[str, str] = {
    "ConnectAccepted": ".connect_accepted",
    "ConnectInboxId": ".connect_inbox_id",
    "ConnectProviderBody": ".connect_provider_body",
    "ListProviderAccountsResponse": ".list_provider_accounts_response",
    "ListProvidersResponse": ".list_providers_response",
    "MagicUrl": ".magic_url",
    "Provider": ".provider",
    "SearchProvidersResponse": ".search_providers_response",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ConnectAccepted",
    "ConnectInboxId",
    "ConnectProviderBody",
    "ListProviderAccountsResponse",
    "ListProvidersResponse",
    "MagicUrl",
    "Provider",
    "SearchProvidersResponse",
]
