# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ...accounts.types.provider_id import ProviderId
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel


class Provider(UncheckedBaseModel):
    """
    A provider an inbox can sign in to.
    """

    provider_id: ProviderId
    name: typing.Optional[str] = None
    updated_at: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Time at which provider was last updated.
    """

    description: typing.Optional[str] = None
    logo_url: typing.Optional[str] = None
    terms_url: typing.Optional[str] = None
    privacy_url: typing.Optional[str] = None
    owner_signup_limit: typing.Optional[int] = pydantic.Field(default=None)
    """
    Maximum number of accounts your organization may sign up at this provider. Omitted when the provider sets no limit. 0 means the provider has paused new sign-ups; existing accounts keep signing in.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
