# This file was auto-generated by Fern from our API Definition.

import typing

from ....core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ....core.request_options import RequestOptions
from ....types.ascending import Ascending
from ....types.limit import Limit
from ....types.page_token import PageToken
from ....webhooks.polling.types.create_polling_webhook_response import CreatePollingWebhookResponse
from ....webhooks.polling.types.list_polling_webhooks_response import ListPollingWebhooksResponse
from ....webhooks.polling.types.polling_client_id import PollingClientId
from ....webhooks.polling.types.polling_webhook import PollingWebhook
from ....webhooks.types.create_webhook_event_types import CreateWebhookEventTypes
from ....webhooks.types.webhook_id import WebhookId
from ...types.inbox_id import InboxId
from .raw_client import AsyncRawPollingClient, RawPollingClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class PollingClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPollingClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPollingClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPollingClient
        """
        return self._raw_client

    def list(
        self,
        inbox_id: InboxId,
        *,
        limit: typing.Optional[Limit] = None,
        page_token: typing.Optional[PageToken] = None,
        ascending: typing.Optional[Ascending] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListPollingWebhooksResponse:
        """
        Lists the polling webhooks created through this inbox route.

        **CLI:**
        ```bash
        agentmail inboxes webhooks polling list --inbox-id <inbox_id>
        ```

        Parameters
        ----------
        inbox_id : InboxId

        limit : typing.Optional[Limit]

        page_token : typing.Optional[PageToken]

        ascending : typing.Optional[Ascending]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListPollingWebhooksResponse

        Examples
        --------
        from agentmail import AgentMail

        client = AgentMail(
            api_key="YOUR_API_KEY",
        )
        client.inboxes.webhooks.polling.list(
            inbox_id="inbox_id",
        )
        """
        _response = self._raw_client.list(
            inbox_id, limit=limit, page_token=page_token, ascending=ascending, request_options=request_options
        )
        return _response.data

    def get(
        self, inbox_id: InboxId, webhook_id: WebhookId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PollingWebhook:
        """
        **CLI:**
        ```bash
        agentmail inboxes webhooks polling get --inbox-id <inbox_id> --webhook-id <webhook_id>
        ```

        Parameters
        ----------
        inbox_id : InboxId

        webhook_id : WebhookId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PollingWebhook

        Examples
        --------
        from agentmail import AgentMail

        client = AgentMail(
            api_key="YOUR_API_KEY",
        )
        client.inboxes.webhooks.polling.get(
            inbox_id="inbox_id",
            webhook_id="webhook_id",
        )
        """
        _response = self._raw_client.get(inbox_id, webhook_id, request_options=request_options)
        return _response.data

    def create(
        self,
        inbox_id: InboxId,
        *,
        client_id: PollingClientId,
        event_types: CreateWebhookEventTypes,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreatePollingWebhookResponse:
        """
        Create a polling webhook scoped to this inbox and return the `token` that reads it.

        **CLI:**
        ```bash
        agentmail inboxes webhooks polling create --inbox-id <inbox_id> --client-id my-agent --event-types message.received
        ```

        Parameters
        ----------
        inbox_id : InboxId

        client_id : PollingClientId

        event_types : CreateWebhookEventTypes

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreatePollingWebhookResponse

        Examples
        --------
        from agentmail import AgentMail

        client = AgentMail(
            api_key="YOUR_API_KEY",
        )
        client.inboxes.webhooks.polling.create(
            inbox_id="inbox_id",
            client_id="client_id",
            event_types=["message.received", "message.received"],
        )
        """
        _response = self._raw_client.create(
            inbox_id, client_id=client_id, event_types=event_types, request_options=request_options
        )
        return _response.data

    def delete(
        self, inbox_id: InboxId, webhook_id: WebhookId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        **CLI:**
        ```bash
        agentmail inboxes webhooks polling delete --inbox-id <inbox_id> --webhook-id <webhook_id>
        ```

        Parameters
        ----------
        inbox_id : InboxId

        webhook_id : WebhookId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from agentmail import AgentMail

        client = AgentMail(
            api_key="YOUR_API_KEY",
        )
        client.inboxes.webhooks.polling.delete(
            inbox_id="inbox_id",
            webhook_id="webhook_id",
        )
        """
        _response = self._raw_client.delete(inbox_id, webhook_id, request_options=request_options)
        return _response.data


class AsyncPollingClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPollingClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPollingClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPollingClient
        """
        return self._raw_client

    async def list(
        self,
        inbox_id: InboxId,
        *,
        limit: typing.Optional[Limit] = None,
        page_token: typing.Optional[PageToken] = None,
        ascending: typing.Optional[Ascending] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListPollingWebhooksResponse:
        """
        Lists the polling webhooks created through this inbox route.

        **CLI:**
        ```bash
        agentmail inboxes webhooks polling list --inbox-id <inbox_id>
        ```

        Parameters
        ----------
        inbox_id : InboxId

        limit : typing.Optional[Limit]

        page_token : typing.Optional[PageToken]

        ascending : typing.Optional[Ascending]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListPollingWebhooksResponse

        Examples
        --------
        import asyncio

        from agentmail import AsyncAgentMail

        client = AsyncAgentMail(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.inboxes.webhooks.polling.list(
                inbox_id="inbox_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(
            inbox_id, limit=limit, page_token=page_token, ascending=ascending, request_options=request_options
        )
        return _response.data

    async def get(
        self, inbox_id: InboxId, webhook_id: WebhookId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PollingWebhook:
        """
        **CLI:**
        ```bash
        agentmail inboxes webhooks polling get --inbox-id <inbox_id> --webhook-id <webhook_id>
        ```

        Parameters
        ----------
        inbox_id : InboxId

        webhook_id : WebhookId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PollingWebhook

        Examples
        --------
        import asyncio

        from agentmail import AsyncAgentMail

        client = AsyncAgentMail(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.inboxes.webhooks.polling.get(
                inbox_id="inbox_id",
                webhook_id="webhook_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(inbox_id, webhook_id, request_options=request_options)
        return _response.data

    async def create(
        self,
        inbox_id: InboxId,
        *,
        client_id: PollingClientId,
        event_types: CreateWebhookEventTypes,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreatePollingWebhookResponse:
        """
        Create a polling webhook scoped to this inbox and return the `token` that reads it.

        **CLI:**
        ```bash
        agentmail inboxes webhooks polling create --inbox-id <inbox_id> --client-id my-agent --event-types message.received
        ```

        Parameters
        ----------
        inbox_id : InboxId

        client_id : PollingClientId

        event_types : CreateWebhookEventTypes

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreatePollingWebhookResponse

        Examples
        --------
        import asyncio

        from agentmail import AsyncAgentMail

        client = AsyncAgentMail(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.inboxes.webhooks.polling.create(
                inbox_id="inbox_id",
                client_id="client_id",
                event_types=["message.received", "message.received"],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            inbox_id, client_id=client_id, event_types=event_types, request_options=request_options
        )
        return _response.data

    async def delete(
        self, inbox_id: InboxId, webhook_id: WebhookId, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        **CLI:**
        ```bash
        agentmail inboxes webhooks polling delete --inbox-id <inbox_id> --webhook-id <webhook_id>
        ```

        Parameters
        ----------
        inbox_id : InboxId

        webhook_id : WebhookId

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from agentmail import AsyncAgentMail

        client = AsyncAgentMail(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.inboxes.webhooks.polling.delete(
                inbox_id="inbox_id",
                webhook_id="webhook_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(inbox_id, webhook_id, request_options=request_options)
        return _response.data
