# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel


class AgentAttachHumanResponse(UncheckedBaseModel):
    """
    Response after attaching a human to an agent organization.
    """

    human_email: str = pydantic.Field()
    """
    Email address of the attached human.
    """

    instructions: str = pydantic.Field()
    """
    Next steps for the agent, in plain text.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
