# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel


class AgentAttachHumanRequest(UncheckedBaseModel):
    """
    Request body to attach a human to an agent organization.
    """

    human_email: str = pydantic.Field()
    """
    Email address of the human who owns the agent. A 6-digit OTP will be sent to this address.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
