# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .authorize_inbox_request import AuthorizeInboxRequest
    from .client_id import ClientId
    from .create_inbox_request import CreateInboxRequest
    from .display_name import DisplayName
    from .email import Email
    from .inbox import Inbox
    from .inbox_id import InboxId
    from .list_inboxes_response import ListInboxesResponse
    from .metadata import Metadata
    from .metadata_value import MetadataValue
    from .search_inboxes_response import SearchInboxesResponse
    from .update_inbox_request import UpdateInboxRequest
    from .update_metadata import UpdateMetadata
_dynamic_imports: typing.Dict[str, str] = {
    "AuthorizeInboxRequest": ".authorize_inbox_request",
    "ClientId": ".client_id",
    "CreateInboxRequest": ".create_inbox_request",
    "DisplayName": ".display_name",
    "Email": ".email",
    "Inbox": ".inbox",
    "InboxId": ".inbox_id",
    "ListInboxesResponse": ".list_inboxes_response",
    "Metadata": ".metadata",
    "MetadataValue": ".metadata_value",
    "SearchInboxesResponse": ".search_inboxes_response",
    "UpdateInboxRequest": ".update_inbox_request",
    "UpdateMetadata": ".update_metadata",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "AuthorizeInboxRequest",
    "ClientId",
    "CreateInboxRequest",
    "DisplayName",
    "Email",
    "Inbox",
    "InboxId",
    "ListInboxesResponse",
    "Metadata",
    "MetadataValue",
    "SearchInboxesResponse",
    "UpdateInboxRequest",
    "UpdateMetadata",
]
