# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...api_keys.types.accept_disclosure import AcceptDisclosure
from ...api_keys.types.auth_token import AuthToken
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel


class AuthorizeInboxRequest(UncheckedBaseModel):
    """
    Authorize one pending AgentID sign-in for the inbox in the path. The
    inbox is selected by the trusted path parameter, never by an AgentID
    `login_hint`.
    """

    auth_token: AuthToken
    accept_disclosure: typing.Optional[AcceptDisclosure] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
