# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...api_keys.types.api_key_id import ApiKeyId
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from ...core.unchecked_base_model import UncheckedBaseModel


class AuthorizeInboxResponse(UncheckedBaseModel):
    """
    The authorized sign-in's key ID plus the agent's next step. The key itself
    is read with Get API Key.
    """

    api_key_id: ApiKeyId = pydantic.Field()
    """
    ID of the public key the client will activate.
    """

    instructions: typing.Literal["Authorization complete. Return to browser."] = pydantic.Field(
        default="Authorization complete. Return to browser."
    )
    """
    The agent's next step. Nothing further is required from the agent.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
