# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .create_inbox_polling_webhook_request import CreateInboxPollingWebhookRequest
    from .create_pod_polling_webhook_request import CreatePodPollingWebhookRequest
    from .create_polling_webhook_request import CreatePollingWebhookRequest
    from .create_polling_webhook_response import CreatePollingWebhookResponse
    from .list_polling_webhooks_response import ListPollingWebhooksResponse
    from .polling_client_id import PollingClientId
    from .polling_token import PollingToken
    from .polling_webhook import PollingWebhook
_dynamic_imports: typing.Dict[str, str] = {
    "CreateInboxPollingWebhookRequest": ".create_inbox_polling_webhook_request",
    "CreatePodPollingWebhookRequest": ".create_pod_polling_webhook_request",
    "CreatePollingWebhookRequest": ".create_polling_webhook_request",
    "CreatePollingWebhookResponse": ".create_polling_webhook_response",
    "ListPollingWebhooksResponse": ".list_polling_webhooks_response",
    "PollingClientId": ".polling_client_id",
    "PollingToken": ".polling_token",
    "PollingWebhook": ".polling_webhook",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "CreateInboxPollingWebhookRequest",
    "CreatePodPollingWebhookRequest",
    "CreatePollingWebhookRequest",
    "CreatePollingWebhookResponse",
    "ListPollingWebhooksResponse",
    "PollingClientId",
    "PollingToken",
    "PollingWebhook",
]
