# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from .polling_token import PollingToken
from .polling_webhook import PollingWebhook


class CreatePollingWebhookResponse(PollingWebhook):
    """
    The subscription plus the one-time `token` that reads it.
    """

    token: PollingToken

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
