# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ....core.unchecked_base_model import UncheckedBaseModel
from ...types.create_webhook_event_types import CreateWebhookEventTypes
from .polling_client_id import PollingClientId


class CreateInboxPollingWebhookRequest(UncheckedBaseModel):
    """
    Create a polling webhook scoped to an inbox. The inbox comes from the path, so `inbox_ids` and
    `pod_ids` are not accepted.
    """

    client_id: PollingClientId
    event_types: CreateWebhookEventTypes

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
