# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ....core.pydantic_utilities import IS_PYDANTIC_V2
from ....core.unchecked_base_model import UncheckedBaseModel
from ....events.types.event_types import EventTypes
from ....events.types.inbox_ids import InboxIds
from ....events.types.pod_ids import PodIds
from ...types.webhook_id import WebhookId
from .polling_client_id import PollingClientId


class PollingWebhook(UncheckedBaseModel):
    """
    A subscription the agent polls for events instead of receiving them at a URL. Same event types,
    channels (pods and inboxes) and permissions as a webhook; no public endpoint is needed.
    """

    webhook_id: WebhookId
    client_id: PollingClientId
    event_types: EventTypes
    pod_ids: typing.Optional[PodIds] = None
    inbox_ids: typing.Optional[InboxIds] = None
    pod_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    ID of the pod the subscription belongs to: the pod it was created in, or the pod of the inbox it
    belongs to. Absent for an organization subscription. This is not the list of pods it receives
    events for; see `pod_ids`.
    """

    inbox_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    ID of the inbox the subscription belongs to, if it was created for an inbox. This is not the
    list of inboxes it receives events for; see `inbox_ids`.
    """

    updated_at: dt.datetime = pydantic.Field()
    """
    Time at which the subscription was last updated.
    """

    created_at: dt.datetime = pydantic.Field()
    """
    Time at which the subscription was created.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
