# This file was auto-generated by Fern from our API Definition.

from ...core.pydantic_utilities import UniversalBaseModel
from .attachment_filename import AttachmentFilename
from .attachment_content_type import AttachmentContentType
from .attachment_content import AttachmentContent
from ...core.pydantic_utilities import IS_PYDANTIC_V2
import typing
import pydantic


class SendAttachment(UniversalBaseModel):
    filename: AttachmentFilename
    content_type: AttachmentContentType
    content: AttachmentContent

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
